SELECT "BU_CODE_DSP" "RCTBUCODEDSP",
       "BU_CODE_CRE_SHP" "RCTBUCODECRESHP",
       "BU_TYPE_CRE_SHP" "RCTBUTYPECRESHP",
       "SHP_NO" "RCTSHPNO",
       "BU_CODE_CRE" "RCTBUCODECRECSM",
       "BU_TYPE_CRE" "RCTBUTYPECRECSM",
       "CSM_NO" "RCTCSMNO",
       "ART_NO" "RCTLINEARTNO",
       TRIM(BOTH
            FROM "ART_NO") "ARTNO",
       "ART_NAME" "ARTNAME",
       "ITEM_TYPE" "RCTLINEITEMTYPE",
       TRUNC(CAST("RCT_DATE_PLND" AS TIMESTAMP(9))) "RCTDATEPLND",
       "TRPT_NO" "RCTTRPNO",
       "RCT_NO" "RCTNO",
       "BU_CODE_RCV" "RCTBUCODERCV",
       "ART_QTY_NOT" "RCTARTQTYNOTI",
       "ART_QTY_PALL" "RCTARTQTYPAL",
       "RCT_SUB_TYPE" "RCTSUBTYPE",
       "BU_TYPE_RCV" "RCTLINEBUTYPERCV",
       "BU_CODE_RCV" "RCTLINEBUCODERCV",
       "BU_ADDRESS_RCV" "RCTLINEBUADDRESSRCV",
       "RCT_STAT" "RCTSTAT",
       "RCTLIN_NO" "RCTLINENO",
       NVL("RCTLIN_SUB_TYPE", ' ') "RCTLINESUBTYPE"
FROM ((("ART_SUP" "ART_SUP"
        INNER JOIN "BO_RECEIPTLINE_V" "BO_RECEIPTLINE_V" ON "ART_NO"="ART_NO"
        AND "SUP_NO"="SUP_NO")
       INNER JOIN "BO_RECEIPT_V" "BO_RECEIPT_V" ON "RCT_NO"="RCT_NO")
      INNER JOIN "ARTICLE" "ARTICLE" ON "ART_NO"="ART_NO")
LEFT OUTER JOIN "BO_RECEIPTLINE_D_V" "BO_RECEIPTLINE_D_V" ON "RCTLIN_NO"="RCTLIN_NO"
AND "RCT_NO"="RCT_NO"
WHERE "RCT_STAT" NOT IN ('4')