
SELECT "O_STOCKBALANCE"."TRANSACTION_ID" AS "TRANSACTION_ID",
       to_char("O_STOCKBALANCE"."TRANS_DATE", 'MM/DD/YY HH:MI AM') AS "TRANS_DATE",
       "O_STOCKBALANCE"."BU_CODE_SEND" AS "BU_CODE_SEND",
       "O_STOCKBALANCE"."BU_TYPE_SEND" AS "BU_TYPE_SEND",
       "O_STOCKBALANCE"."ITEM_NO" AS "ITEM_NO",
       "O_STOCKBALANCE"."ITEM_TYPE" AS "ITEM_TYPE",
       "O_STOCKBALANCE"."BU_CODE_SUP" AS "BU_CODE_SUP",
       "O_STOCKBALANCE"."BU_TYPE_SUP" AS "BU_TYPE_SUP",
       SUM("O_STOCKBALANCE"."ART_QTY") AS "ART_QTY",
       SUM("O_STOCKBALANCE"."ART_QTY_QSTOP") AS "ART_QTY_QSTOP",
       SUM("O_STOCKBALANCE"."ART_QTY_LSTOP") AS "ART_QTY_LSTOP"
FROM "GEMINI"."O_STOCKBALANCE" "O_STOCKBALANCE"
GROUP BY "O_STOCKBALANCE"."TRANSACTION_ID",
         to_char("O_STOCKBALANCE"."TRANS_DATE", 'MM/DD/YY HH:MI AM'),
         "O_STOCKBALANCE"."BU_CODE_SEND",
         "O_STOCKBALANCE"."BU_TYPE_SEND",
         "O_STOCKBALANCE"."ITEM_NO",
         "O_STOCKBALANCE"."ITEM_TYPE",
         "O_STOCKBALANCE"."BU_CODE_SUP",
         "O_STOCKBALANCE"."BU_TYPE_SUP"
ORDER BY "TRANSACTION_ID" ASC NULLS LAST,
         "ITEM_NO" ASC NULLS LAST