
SELECT "BO_DISPATCH_V"."BU_CODE_RCV" "DSPBuCodeRCV",
       "BO_DISPATCH_V"."BU_TYPE_RCV" "DSPBuTypeRCV",
       "BO_ORDERS_V"."ART_NO" "ORDArtNo",
       to_number(to_char("BO_ORDERS_V"."ORD_DATE_REG", 'IW')) "ORDDateReg__Week_",
       count("BO_ORDERS_V"."ORD_ID") "ORDOrderId",
       sum("BO_ORDERS_V"."ART_QTY_DEL") "ORDSumDeliveredQty",
       substr(TRUNC(cast("BO_ORDERS_V"."ORD_DATE_REG" AS TIMESTAMP(9))), 8, 10) "ORDDateReg",
       "DIVISION"."CTY_CODE" "DSPDivCtyCode"
FROM ((("ART_SUP" "ART_SUP"
        INNER JOIN "BO_ORDERS_V" "BO_ORDERS_V" ON "ART_SUP"."ART_NO"="BO_ORDERS_V"."ART_NO"
        AND "ART_SUP"."SUP_NO"="BO_ORDERS_V"."SUP_NO")
       INNER JOIN "BO_DISPATCHUNIT_V" "BO_DISPATCHUNIT_V" ON "BO_ORDERS_V"."DSPUNIT_NO"="BO_DISPATCHUNIT_V"."DSPUNIT_NO"
       AND "BO_ORDERS_V"."DSPUNIT_TYPE"="BO_DISPATCHUNIT_V"."DSPUNIT_TYPE"
       AND nvl(to_char("BO_ORDERS_V"."ARC_DATE", 'DD-MON-YY'), '01-JAN-50')=nvl(to_char("BO_DISPATCHUNIT_V"."ARC_DATE", 'DD-MON-YY'), '01-JAN-50'))
      INNER JOIN "BO_DISPATCH_V" "BO_DISPATCH_V" ON "BO_DISPATCH_V"."ARC_DATE_FILLED"="BO_DISPATCHUNIT_V"."ARC_DATE_FILLED"
      AND "BO_DISPATCH_V"."DSP_NO"="BO_DISPATCHUNIT_V"."DSP_NO")
LEFT OUTER JOIN "DIVISION" "DIVISION" ON "BO_ORDERS_V"."BU_CODE_RCV"="DIVISION"."BU_CODE"
AND "BO_ORDERS_V"."BU_TYPE_RCV"="DIVISION"."BU_TYPE"
WHERE "BO_ORDERS_V"."ART_QTY"<"ART_SUP"."ART_QTY_PALL"
  AND to_number(to_char("BO_ORDERS_V"."ORD_DATE_REG", 'IW')) BETWEEN CAST(:PQ1 AS DOUBLE PRECISION) AND CAST(:PQ2 AS DOUBLE PRECISION)
GROUP BY "BO_DISPATCH_V"."BU_CODE_RCV",
         "BO_DISPATCH_V"."BU_TYPE_RCV",
         "BO_ORDERS_V"."ART_NO",
         to_number(to_char("BO_ORDERS_V"."ORD_DATE_REG", 'IW')),
         substr(TRUNC(cast("BO_ORDERS_V"."ORD_DATE_REG" AS TIMESTAMP(9))), 8, 10),
         "DIVISION"."CTY_CODE"
HAVING count("BO_ORDERS_V"."ORD_ID")>1