SELECT DISTINCT trim(BOTH
                     FROM "G08T1"."MHA") "StoPal_MHA",
                substr("L62T13"."PARTNO", 1, 8) "ArtFea_ArticleNo",
                trim(BOTH
                     FROM "L62T13"."PARTREV") "ArtFea_SupNo",
                "G08T1"."AMOONCR" "StoPal_PallQty",
                "G08T1"."CARRSTAT" "StoPal_PallStat",
                "G08T1"."CARRTYPE" "StoPal_PallType",
                "G08T1"."RACK" "StoPal_Rack",
                "G08T1"."HORCOOR" "StoPal_HorCoor",
                trim(BOTH
                     FROM "G08T1"."VERCOOR") "StoPal_VerCoor",
                "G08T1"."LDCT" "StoPal_PallClass",
                ("G08T1"."AMOONCR"*"L62T13"."PARTVOL")/1000 "StoPal_PallVol",
                "L62T13"."SHORTL62" "ArtFea_RefKey_L62",
                "G08T1"."ECARRNO" "StoPal_Pallid",
                to_number(to_char(trunc(sysdate), 'WW')) "TI_Current_WeekNo_first_day",
                TRUNC(cast(sysdate AS TIMESTAMP(9))) "TI_Today",
                "G08T1"."CARRWGHT" "StoPal_PallWght",
                "L62T13"."FIRECODE" "ARTFireClass",
                TRUNC(cast(sysdate AS TIMESTAMP(9))) "TI_Today1"
FROM "G08T1" "G08T1",
     "L62T13"
WHERE "G08T1"."CARRSTAT" IN (6)
  AND trim(BOTH
           FROM "G08T1"."MHA") IN ('10R1',
                                   '11MW',
                                   '11PA',
                                   '11R',
                                   '11R1',
                                   '11RPH',
                                   '11RPN',
                                   '11RPT',
                                   '12MW',
                                   '12PA',
                                   '12R1',
                                   '12R1H',
                                   '27F',
                                   '29DF',
                                   '30F',
                                   '31F1',
                                   '32DF',
                                   '36R2',
                                   '3R',
                                   '3R1',
                                   '41R',
                                   '42F',
                                   '42PUP',
                                   '32GA',
                                   '33F1',
                                   '34R',
                                   '34R1',
                                   '35R1',
                                   '36R1',
                                   '12RPH',
                                   '12RPN',
                                   '12RPT',
                                   '13PA',
                                   '13R1',
                                   '13R1H',
                                   '13R1T',
                                   '13RPN',
                                   '13RPT',
                                   '14PH',
                                   '14PIC',
                                   '14PMH',
                                   '14PS',
                                   '14PSH',
                                   '14R',
                                   '14R1',
                                   '14R1H',
                                   '14R1N',
                                   '14RPH',
                                   '14RPN',
                                   '14RPT',
                                   '14RS',
                                   '15PBR',
                                   '15PMH',
                                   '15R',
                                   '15R1',
                                   '15R1N',
                                   '15R1T',
                                   '15RPH',
                                   '15RPN',
                                   '15RPT',
                                   '16NBB',
                                   '16PG0',
                                   '16PG1',
                                   '16PG2',
                                   '16PMH',
                                   '16R',
                                   '16R1N',
                                   '16R1T',
                                   '16RPN',
                                   '16RPT',
                                   '17PMH',
                                   '17PV',
                                   '17R1H',
                                   '17R1N',
                                   '17R1T',
                                   '17RPH',
                                   '17RPN',
                                   '19R',
                                   '24A',
                                   '24F',
                                   '25A',
                                   '25F',
                                   '26F',
                                   '43F',
                                   '43R',
                                   '44R',
                                   '45R',
                                   '46R',
                                   '48B2B',
                                   '4R',
                                   '4R1',
                                   '69',
                                   '6R',
                                   '6R1',
                                   '846P',
                                   'AP10',
                                   'AP18',
                                   'AP840',
                                   'NP12',
                                   'NP17',
                                   'NP20',
                                   'NP34',
                                   'NP4',
                                   'NP45',
                                   'NP845',
                                   'NP846',
                                   'Q2',
                                   'REAC0',
                                   'REAC1',
                                   'REAC2',
                                   'RETC2',
                                   'SPRIN',
                                   'TORN1',
                                   'TORN2',
                                   'TORN3',
                                   'TR4SO',
                                   '11PHG',
                                   '12PHG',
                                   '12PL',
                                   '13PL')
  AND NOT "G08T1"."AMOONCR" IS NULL
  AND "L62T13"."SHORTL62"="G08T1"."SHORTL62"