
SELECT DISTINCT "YMT11T1"."ELUID" "YUniLu_LoadingUnit",
                "YMT11T1"."CARRIER" "YUniLu_Carrier",
                "YMT11T1"."UPDDATE" "YUniLu_UpdDate",
                (TRUNC(CAST("YMT11T1"."UPDDATE" AS TIMESTAMP)) - TRUNC(CAST(sysdate AS TIMESTAMP))) "c4",
                "YMT11T1"."PLUSTAT" "YUniLu_PhysStat",
                "YMT11T1"."LUSTATUS" "YUniLu_LuStat",
                "YMT11T1"."LUOWNER" "YUniLu_Owner"
FROM "YMT11T1" "YMT11T1"
WHERE "YMT11T1"."PLUSTAT">0
  AND "YMT11T1"."CARRIER" IN ('BARRON WOOD DIS',
                              'C.H. ROBINSON E',
                              'CODOGNOTTO ITAL',
                              'CONTAINERSHIPS ',
                              'DFDS LOGISTICS ',
                              'DSV            ',
                              'EDDIE STOBART L',
                              'Eddie Stobart  ',
                              'Electrolux     ',
                              'GEODIS Poland S',
                              'GIRTEKA        ',
                              'GIRTEKA EUROPE ',
                              'GOPET TRANS EOO',
                              'GRUBER LOGISTI1',
                              'Hatfields      ',
                              'INSTAFREIGHT GM',
                              'K-LOG LOGISTICA',
                              'LKW WALTER INTE',
                              'MARITIME TRANSP',
                              'NOTHEGGER TRANS',
                              'P&O FERRYMASTE1',
                              'PEKAES SP. Z O.',
                              'PODLASIE S.A.  ',
                              'SAMSKIP MULTIMO',
                              'SENNDER DEUTSCH',
                              'TRANSMEC RO SRL',
                              'UAB INTEGRE TRA',
                              'UAB TRANSEKSPED',
                              'UNIFEEDER A/S  ',
                              'W H MALCOLM  LT',
                              'WABERER:S INTE2',
                              'WOODSIDE HAULAG',
                              'XPO Transport S',
                              'CMA CGM (Hollan',
                              'CMA CGM (HOLLAN',
                              'W H MALCOLM LTD',
                              'UNISERVE LIMITE')
  AND "YMT11T1"."ELUID" not  like 'MDL%'
  AND "YMT11T1"."LUSTATUS" BETWEEN 1 AND 1
  AND (TRUNC(CAST("YMT11T1"."UPDDATE" AS TIMESTAMP)) - TRUNC(CAST(sysdate AS TIMESTAMP)))<0