
SELECT "BO_ORDERS_V"."ORD_SENDER" "ORDOrdsender",
       "BO_ORDERS_V"."SRC_NAME_ORD" "ORDOrdSRCNameORD",
       TRUNC(cast("BO_ORDERS_V"."ORD_DATE_REG" AS TIMESTAMP(9))) "ORDDateReg",
       "BO_ORDERS_V"."BU_TYPE_RCV" "ORDOrdBuTypeRCV",
       "BO_ORDERS_V"."BU_CODE_RCV" "ORDOrdBuCodeRCV",
       "BO_ORDERS_V"."ORD_CLASS" "ORDOrderClass",
       "DIVISION"."CTY_CODE" "DSPDivCtyCode",
       "BO_ORDERS_V"."ART_NO" "ORDArtNo",
       sum(("BO_ORDERS_V"."ART_QTY"*"BO_ORDERS_V"."ART_VOL_GRO")/1000) "ORDOrderVol",
       ("BO_ORDERS_V"."ART_QTY_DEL"*"ART_SUP"."ART_VOL_GRO")/1000 "ORDDeliveredVol",
       "BO_ORDERS_V"."ORD_STAT" "ORDOrderStatus",
       "BO_ORDERS_V"."ORD_ID" "ORDOrderId",
       "BO_ORDERS_V"."ART_QTY" "ORDOrderQty",
       TRUNC(cast("BO_ORDERS_V"."ARR_DATE_REQ" AS TIMESTAMP(9))) "ORDArrDateReq",
       TRUNC(cast("BO_ORDERS_LEADTIME_V"."DSP_DATE_PLAN" AS TIMESTAMP(9))) "ORDDspDatePlan",
       "BO_ORDERS_V"."SUBADR_NO" "ORDSubadrNo",
       "BO_ORDERS_V"."SUBADR_GRP" "ORDSubadrGrp",
       SUBSTR("ARTICLE"."PA_NO", 1, 2) "ARTBaNo",
       "ARTICLE"."PA_NO" "ARTPaNo",
       "ARTICLE"."ART_NAME" "ARTName",
       "BO_ORDERS_V"."LOC_PRIORITY" "ORDOrdLoc_Priority",
       "BO_ORDERS_V"."ART_QTY_DEL" "ORDDeliveredQty",
       TRUNC(cast("BO_ORDERS_V"."ARC_DATE" AS TIMESTAMP(9))) "ORDArcDate",
       "BO_ORDERS_V"."ORD_DATE_REG" "ORDDateTimeReg"
FROM ((("ART_SUP" "ART_SUP"
        INNER JOIN "BO_ORDERS_V" "BO_ORDERS_V" ON "ART_SUP"."ART_NO"="BO_ORDERS_V"."ART_NO"
        AND "ART_SUP"."SUP_NO"="BO_ORDERS_V"."SUP_NO")
       INNER JOIN "BO_ORDERS_LEADTIME_V" "BO_ORDERS_LEADTIME_V" ON "BO_ORDERS_V"."ORD_ID"="BO_ORDERS_LEADTIME_V"."ORD_ID")
      INNER JOIN "ARTICLE" "ARTICLE" ON "ARTICLE"."ART_NO"="ART_SUP"."ART_NO")
LEFT OUTER JOIN "DIVISION" "DIVISION" ON "BO_ORDERS_V"."BU_CODE_RCV"="DIVISION"."BU_CODE"
AND "BO_ORDERS_V"."BU_TYPE_RCV"="DIVISION"."BU_TYPE"
WHERE "BO_ORDERS_V"."ORD_CLASS">0
  AND TRUNC(cast("BO_ORDERS_V"."ORD_DATE_REG" AS TIMESTAMP(9))) BETWEEN TRUNC(cast(:PQ1 AS TIMESTAMP(9))) AND TRUNC(cast(:PQ2 AS TIMESTAMP(9)))
GROUP BY "BO_ORDERS_V"."ORD_SENDER",
         "BO_ORDERS_V"."SRC_NAME_ORD",
         TRUNC(cast("BO_ORDERS_V"."ORD_DATE_REG" AS TIMESTAMP(9))),
         "BO_ORDERS_V"."BU_TYPE_RCV",
         "BO_ORDERS_V"."BU_CODE_RCV",
         "BO_ORDERS_V"."ORD_CLASS",
         "DIVISION"."CTY_CODE",
         "BO_ORDERS_V"."ART_NO",
         ("BO_ORDERS_V"."ART_QTY_DEL"*"ART_SUP"."ART_VOL_GRO")/1000,
         "BO_ORDERS_V"."ORD_STAT",
         "BO_ORDERS_V"."ORD_ID",
         "BO_ORDERS_V"."ART_QTY",
         TRUNC(cast("BO_ORDERS_V"."ARR_DATE_REQ" AS TIMESTAMP(9))),
         TRUNC(cast("BO_ORDERS_LEADTIME_V"."DSP_DATE_PLAN" AS TIMESTAMP(9))),
         "BO_ORDERS_V"."SUBADR_NO",
         "BO_ORDERS_V"."SUBADR_GRP",
         SUBSTR("ARTICLE"."PA_NO", 1, 2),
         "ARTICLE"."PA_NO",
         "ARTICLE"."ART_NAME",
         "BO_ORDERS_V"."LOC_PRIORITY",
         "BO_ORDERS_V"."ART_QTY_DEL",
         TRUNC(cast("BO_ORDERS_V"."ARC_DATE" AS TIMESTAMP(9))),
         "BO_ORDERS_V"."ORD_DATE_REG"