SELECT DISTINCT "SQL1"."DSP_DATE_ACT" "DSP_DATE_ACT",
                "SQL1"."ORD_DATE_REG" "ORD_DATE_REG",
                "SQL1"."CREATE_DATE_ORD" "CREATE_DATE_ORD",
                "SQL1"."BU_TYPE_CRE" "BU_TYPE_CRE",
                "SQL1"."BU_CODE_CRE" "BU_CODE_CRE",
                "SQL1"."DSP_TYPE" "DSP_TYPE",
                "SQL1"."BU_CODE_RCV" "BU_CODE_RCV",
                "SQL1"."BU_TYPE_RCV" "BU_TYPE_RCV",
                "SQL1"."RCV_NAME" "RCV_NAME",
                "SQL1"."SHP_NO" "SHP_NO",
                "SQL1"."CSM_NO" "CSM_NO",
                "SQL1"."ORD_ID" "ORD_ID",
                "SQL1"."ORDER_TYPE" "ORDER_TYPE",
                "SQL1"."ORD_CLASS" "ORD_CLASS",
                "SQL1"."ART_CODE_PALL" "ART_CODE_PALL",
                "SQL1"."ART_CODE_PLOCK" "ART_CODE_PLOCK",
                "SQL1"."Pick Type MIP" "Pick_Type_MIP",
                "SQL1"."PALL_ID" "PALL_ID",
                "SQL1"."ART_NO" "ART_NO",
                "SQL1"."SUP_NO" "SUP_NO",
                "SQL1"."ARTSUP" "ARTSUP",
                "SQL1"."PA_NO" "PA_NO",
                "SQL1"."PBA_NO" "PBA_NO",
                "SQL1"."Unit Volume" "Unit_Volume",
                "SQL1"."ART_PRI_CALC_17" "ART_PRI_CALC_17",
                "SQL1"."ART_PRICE" "ART_PRICE",
                "SQL1"."ART_QTY_DEL" "ART_QTY_DEL",
                "SQL1"."ART_VOL_GRO" "ART_VOL_GRO",
                "SQL1"."Price (TT201)" "Price__TT201_",
                "SQL1"."Orders" "Orders",
                "SQL1"."Pallets" "Pallets",
                "SQL1"."ART_QTY_PALL" "ART_QTY_PALL",
                "SQL1"."ART_QTY_MPACK_SYS" "ART_QTY_MPACK_SYS"
FROM "SQL1"