SELECT AL2.PARTNO,
       AL2.PARTREV,
       AL2.PARTDSC1,
       AL2.DIVCODE,
       AL3.MHA,
       AL3.RACK,
       AL3.HORCOOR,
       AL3.VERCOOR,
       AL1.ECARRNO,
       AL1.AMOONCR,
       AL1.LOCKCODE
FROM AST021.G08T1 AL1,
     AST021.L62T1 AL2,
     AST021.L34T1 AL3
WHERE (AL1.SHORTL62 = AL2.SHORTL62
       AND AL3.MHA = AL1.MHA
       AND AL3.RACK = AL1.RACK
       AND AL3.HORCOOR = AL1.HORCOOR
       AND AL3.VERCOOR = AL1.VERCOOR
       AND AL3.CARRNO = AL1.CARRNO)
  AND (AL1.CARRSTAT IN (5,
                        6)
       AND TRIM(AL2.DIVCODE) = '053'
       AND TRIM(AL2.partno) <> 'TOTE')