
SELECT "A_L62T1_X08T3"."SUVOL",
       "X08T37"."X08QUANT",
       trim(BOTH
            FROM "X08T37"."PARTREV"),
       substr("X08T37"."PARTNO", 1, 8),
       "X08T37"."DATREG",
       trim(BOTH
            FROM "X08T37"."LOGGUSER"),
       "X08T37"."X08RCODE",
       trim(BOTH
            FROM "X08T37"."PARTNO")
FROM
  (SELECT "X08T3"."DATREG" "DATREG",
          "X08T3"."LOGGUSER" "LOGGUSER",
          "X08T3"."PARTNO" "PARTNO",
          "X08T3"."PARTREV" "PARTREV",
          "X08T3"."X08QUANT" "X08QUANT",
          "X08T3"."X08RCODE" "X08RCODE"
   FROM "X08T3" "X08T3"
   WHERE trim(BOTH
              FROM "X08T3"."DIVCODE") NOT IN ('----')) "X08T37"
INNER JOIN
  (SELECT "L62T1"."PARTNO" "PARTNO",
          "L62T1"."PARTREV" "PARTREV",
          "L62T1"."SUVOL" "SUVOL"
   FROM "L62T1" "L62T1"
   WHERE trim(BOTH
              FROM "L62T1"."DIVCODE") NOT IN ('----')) "A_L62T1_X08T3" ON "X08T37"."PARTNO"="A_L62T1_X08T3"."PARTNO"
AND "X08T37"."PARTREV"="A_L62T1_X08T3"."PARTREV"
WHERE "X08T37"."X08RCODE"='220'
  AND TRUNC(cast("X08T37"."DATREG" AS TIMESTAMP(9)))<=TRUNC(cast(:PQ2 AS TIMESTAMP(9)))
  AND TRUNC(cast("X08T37"."DATREG" AS TIMESTAMP(9)))>=TRUNC(cast(:PQ1 AS TIMESTAMP(9)))
  SELECT "A_PRICES_X08T3"."PRICE",
         "A_PRICES_X08T3"."ITEM_NO",
         "A_PRICES_X08T3"."BU_CODE_SUP", (coalesce("A_PRICES_X08T3"."BU_TYPE_SUP", 'SUP'))
  FROM
    (SELECT "PRICES_VW"."ITEM_TYPE" "ITEM_TYPE",
            "PRICES_VW"."ITEM_NO" "ITEM_NO",
            "PRICES_VW"."BU_TYPE_SUP" "BU_TYPE_SUP",
            "PRICES_VW"."BU_CODE_SUP" "BU_CODE_SUP",
            "PRICES_VW"."PRICE" "PRICE"
     FROM "PRICES_VW" "PRICES_VW"
     WHERE "PRICES_VW"."BU_TYPE"='CDC'
       AND "PRICES_VW"."BU_CODE" IN ('418')
       AND "PRICES_VW"."ITEM_TYPE"='ART') "A_PRICES_X08T3"