
SELECT "T0"."C0" "STOChgPallid",
       "T0"."C1" "STOChgTyp",
       "T0"."C2" "STOChgDate",
       "T0"."C3" "STOChgTime",
       "T0"."C4" "STOChgUser",
       "T0"."C5" "STOChgArtNo",
       "T0"."C6" "STOChgSupNo",
       "T0"."C7" "STOChgQty",
       "T0"."C8" "STOArtPriceInve",
       min("T0"."C9") OVER (PARTITION BY "T0"."C0", "T0"."C1", "T0"."C2", "T0"."C3", "T0"."C4", "T0"."C5", "T0"."C6", "T0"."C8", "T0"."C10") "Valeur_TT",
       abs(min("T0"."C9") OVER (PARTITION BY "T0"."C0", "T0"."C1", "T0"."C2", "T0"."C3", "T0"."C4", "T0"."C5", "T0"."C6", "T0"."C8", "T0"."C10")) "Valeur_absolue__Valeur_TT_",
       "T0"."C10" "Week"
FROM
  (SELECT "BO_PALL_CHG_LOG_V"."PALL_ID" "C0",
          "BO_PALL_CHG_LOG_V"."CHG_TYPE" "C1",
          TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))) "C2",
          to_char(to_date("BO_PALL_CHG_LOG_V"."CHG_TIME", 'sssss'), 'HH24:mi:ss') "C3",
          "BO_PALL_CHG_LOG_V"."USER_ID" "C4",
          "BO_PALL_CHG_LOG_V"."ART_NO" "C5",
          "BO_PALL_CHG_LOG_V"."SUP_NO" "C6",
          sum("BO_PALL_CHG_LOG_V"."ART_QTY") "C7",
          "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE" "C8",
          sum("BO_PALL_CHG_LOG_V"."ART_QTY")*"BO_PALL_CHG_LOG_V"."ART_PRICE_INVE" "C9",
          to_char(TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))), 'iw') "C10"
   FROM "BO_PALL_CHG_LOG_V" "BO_PALL_CHG_LOG_V"
   WHERE "BO_PALL_CHG_LOG_V"."CHG_TYPE" IN ('313',
                                            '314',
                                            '390',
                                            '391',
                                            '392',
                                            '394',
                                            '305',
                                            '306',
                                            '316',
                                            '310',
                                            '317',
                                            '315',
                                            '260',
                                            '440',
                                            '441',
                                            '437',
                                            '457',
                                            '460',
                                            '461',
                                            '318',
                                            '308',
                                            '450',
                                            '451',
                                            '439',
                                            '459',
                                            '435',
                                            '455',
                                            '320',
                                            '321',
                                            '393')
     AND to_char(TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))), 'iw')>=to_number(to_char(trunc(sysdate), 'IW')) - 1
     AND TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9)))>=TRUNC(cast(sysdate AS TIMESTAMP(9))) - 10
   GROUP BY "BO_PALL_CHG_LOG_V"."PALL_ID",
            "BO_PALL_CHG_LOG_V"."CHG_TYPE",
            TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))),
            to_char(to_date("BO_PALL_CHG_LOG_V"."CHG_TIME", 'sssss'), 'HH24:mi:ss'),
            "BO_PALL_CHG_LOG_V"."USER_ID",
            "BO_PALL_CHG_LOG_V"."ART_NO",
            "BO_PALL_CHG_LOG_V"."SUP_NO",
            "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE",
            to_char(TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))), 'iw')) "T0"