SELECT AL1.BU_CODE_DT_FILL,
       AL1.BU_CODE_RCV,
       AL4.NAME,
       AL3.PA_NO,
       AL1.ITEM_ID,
       AL3.NAME_PRIME,
       AL1.LOCATION_PRIO,
       AL1.ORDER_DATE,
       CONCAT(CONCAT(AL1.ORDER_TYPE, '-'), AL6.NAME) AS OrderType,
       CONCAT(CONCAT(AL1.STATUS, '-'), AL7.NAME) AS OrderStatus,
       AL1.ITEM_QTY_ORD,
       AL1.ITEM_QTY_DSP,
       AL1.DSP_DATE_LATEST,
       AL1.MHS_ORD_TYPE,
       AL1.MHS_DEL_TYPE,
       AL4.CTY_CODE,
       ((((AL9.ITEM_LEN/100)* (AL9.ITEM_WID/100)* (AL9.ITEM_HEI/100)) / 1000)) AS ItemVol
FROM GEMINI.ORDERS AL1,
     GEMINI.ITEM_WITH_NAME AL3,
     GEMINI.STORE AL4,
     GEMINI.ORDER_TYPE_DICT AL6,
     GEMINI.ORDER_STATUS_DICT AL7,
     GEMINI.ITEM_DT AL8,
     GEMINI.ITEM_SUP AL9
WHERE (AL3.ITEM_ID =AL1.ITEM_ID
       AND AL1.ITEM_TYPE =AL3.ITEM_TYPE
       AND AL4.BU_CODE =AL1.BU_CODE_RCV
       AND AL1.BU_TYPE_RCV =AL4.BU_TYPE
       AND AL1.ORDER_TYPE =AL6.ORDER_TYPE
       AND AL7.ORDER_STATUS =AL1.STATUS
       AND AL8.ITEM_ID =AL1.ITEM_ID
       AND AL8.BU_CODE_DT =AL1.BU_CODE_DT_FILL
       AND AL9.ITEM_ID =AL8.ITEM_ID
       AND AL9.BU_CODE_SUP =AL8.BU_CODE_SUP_PREF)
  AND (((NOT AL1.STATUS ='99')
        AND TRUNC(AL1.ORDER_DATE) >= TRUNC (Sysdate - 7)
        AND AL1.BU_TYPE_RCV ='STO'
        AND AL1.ORDER_TYPE IN ('FSR',
                               'MSR',
                               'R')
        AND AL1.BU_TYPE_DT_FILL ='DT'))