SELECT DISTINCT TRUNC(cast("O04T14"."DELDATE" AS TIMESTAMP(9))) "OrdGi_Deldate",
                TRUNC(cast("O04T14"."REGDATE" AS TIMESTAMP(9))) "OrdGi_RegDate",
                "O04T14"."ORDNO" "OrdGi_OrdNo",
                "O04T14"."ORDSTAT" "OrdGi_OrdStat",
                "O04T90"."RCVBUCOD" "OrdGi_BU_Code",
                "O08T15"."PARTNO" "OrdGi_O08_ArtNo",
                "O04T14"."ORDTYPE" "OrdGi_Ordtype",
                "O04T90"."PMCODE" "OrdGi_Pmcode",
                "O04T90"."LOCPRIO" "OrdGi_Locprio",
                TRUNC(cast(sysdate AS TIMESTAMP(9))) "TI_Today",
                "O04T90"."ORDPLTYP" "OrdGi_Ordpltype"
FROM "O04T14",
     "O04T90" "O04T90",
     "O08T15"
WHERE "O04T14"."ORDSTAT" IN (1,
                             2,
                             4,
                             6,
                             7,
                             22)
  AND "O04T90"."RCVBUCOD" IN ('027    ',
                              '028    ',
                              '030    ',
                              '113    ',
                              '125    ',
                              '140    ',
                              '141    ',
                              '142    ',
                              '143    ',
                              '144    ',
                              '150    ',
                              '185    ',
                              '186    ',
                              '255    ',
                              '261    ',
                              '262    ',
                              '263    ',
                              '264    ',
                              '265    ',
                              '266    ',
                              '267    ',
                              '269    ',
                              '461    ',
                              '519    ',
                              '548    ',
                              '567    ',
                              '642    ')
  AND "O08T15"."DIVCODE"="O04T14"."DIVCODE"
  AND "O08T15"."ORDNO"="O04T14"."ORDNO"
  AND "O08T15"."SHORTO04"="O04T14"."SHORTO04"
  AND "O04T90"."SHORTO04"="O04T14"."SHORTO04"