SELECT "SQL1"."CDC" "CDC", 
       "SQL1"."STATDATE" "STATDATE", 
       "SQL1"."Aging Hours" "Aging_Hours", 
       "SQL1"."MHA" "MHA", 
       "SQL1"."Location" "Location", 
       "SQL1"."Dock Door" "Dock_Door", 
       "SQL1"."Package ID" "Package_ID", 
       "SQL1"."Article" "Article", 
       "SQL1"."Revision" "Revision", 
       "SQL1"."AMOONCR" "AMOONCR", 
       "SQL1"."Full / Partial" "Full___Partial", 
       "SQL1"."FPQ" "FPQ", 
       "SQL1"."Available" "Available", 
       "SQL1"."Block Code" "Block_Code", 
       "SQL1"."Reserved" "Reserved", 
       "SQL1"."To MHA" "To_MHA", 
       "SQL1"."LdCT" "LdCT", 
       "SQL1"."Pallet Class" "Pallet_Class", 
       "SQL1"."HFB" "HFB", 
       "SQL1"."HFB Definition" "HFB_Definition", 
       "SQL1"."Multi-box?" "Multi_box_", 
       "SQL1"."Num PCS" "Num_PCS", 
       "SQL1"."Art Volume" "Art_Volume", 
       "SQL1"."Pick MHA" "Pick_MHA", 
       "SQL1"."Pick Zone" "Pick_Zone", 
       "SQL1"."Buffer MHA" "Buffer_MHA", 
       "SQL1"."Carrno" "Carrno", 
       "SQL1"."Short L62" "Short_L62", 
       "SQL1"."Days Aging" "Days_Aging", 
       "SQL1"."Aging > 48 H" "Aging___48_H", 
       sum("SQL1"."Net Volume") "Total_Net_Volume", 
       sum(1) "Total_Pallets", 
       sum(CASE 
               WHEN "SQL1"."Aging Hours">=24 THEN '1' 
               ELSE '0'
           END) "Pallets_Aging___24_H"
FROM "SQL1"
GROUP BY "SQL1"."CDC",
         "SQL1"."STATDATE",
         "SQL1"."Aging Hours",
         "SQL1"."MHA",
         "SQL1"."Location",
         "SQL1"."Dock Door",
         "SQL1"."Package ID",
         "SQL1"."Article",
         "SQL1"."Revision",
         "SQL1"."AMOONCR",
         "SQL1"."Full / Partial",
         "SQL1"."FPQ",
         "SQL1"."Available",
         "SQL1"."Block Code",
         "SQL1"."Reserved",
         "SQL1"."To MHA",
         "SQL1"."LdCT",
         "SQL1"."Pallet Class",
         "SQL1"."HFB",
         "SQL1"."HFB Definition",
         "SQL1"."Multi-box?",
         "SQL1"."Num PCS",
         "SQL1"."Art Volume",
         "SQL1"."Pick MHA",
         "SQL1"."Pick Zone",
         "SQL1"."Buffer MHA",
         "SQL1"."Carrno",
         "SQL1"."Short L62",
         "SQL1"."Days Aging",
         "SQL1"."Aging > 48 H"