
SELECT DISTINCT "L16T3"."DATREG" "IMH_RegDateTime",
                "L16T3"."LOGGUSER" "IMH_LoggUser",
                "L16T3"."L16LCODE" "IMH_LoggCode",
                "L16T3"."PARTNO" "IMH_L16_Art_No",
                "L16T3"."PARTREV" "IMH_L16_Sup_No",
                trim(BOTH
                     FROM "L16T3"."ECARRNO") "IMH_StUn",
                "L16T3"."FMHA" "IMH_FromMHA",
                "L16T3"."FRACK" "IMH_FromRack",
                "L16T3"."FVERCOOR" "IMH_FromLevel",
                concat(concat("L16T3"."FRACK", "L16T3"."FHORCOOR"), ltrim("L16T3"."FVERCOOR")) "IMH_FromPlaceNo",
                "L16T3"."MHA" "IMH_ToMHA",
                "L16T3"."RACK" "IMH_ToRack",
                "L16T3"."VERCOOR" "IMH_ToLevel",
                "L16T3"."L16QTY" "IMH_PickQty",
                "L16T3"."L16WGHT" "IMH_PickWght",
                "L16T3"."SHORTL62" "IMH_Shortl62",
                "L16T3"."ADMUNIT" "IMH_Queue",
                "L16T3"."DIVCODE" "IMH_DivCode"
FROM "L16T3" "L16T3"
WHERE "L16T3"."L16LCODE" IN (3)
  AND "L16T3"."DATREG">=to_date('2025-03-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
  AND "L16T3"."DATREG"<(to_date('2025-03-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS') + INTERVAL '1' DAY)
  AND "L16T3"."PARTNO" NOT IN ('packed goods            ')
  AND "L16T3"."FMHA" IN ('AP10 ',
                         'AP11 ',
                         'AP12 ',
                         'AP13 ',
                         'AP14 ',
                         'AP15 ',
                         'AP16 ',
                         'AP17 ',
                         'AP18 ',
                         'AP19 ',
                         'AP1PH',
                         'AP2  ',
                         'AP20 ',
                         'AP21 ',
                         'AP28 ',
                         'AP2H ',
                         'AP2PN',
                         'AP2PT',
                         'AP3  ',
                         'AP32 ',
                         'AP34 ',
                         'AP35 ',
                         'AP36 ',
                         'AP3PT',
                         'AP4  ',
                         'AP41 ',
                         'AP43 ',
                         'AP44 ',
                         'AP45 ',
                         'AP46 ',
                         'AP47 ',
                         'AP48 ',
                         'AP49 ',
                         'AP4PH',
                         'AP4PT',
                         'AP5  ',
                         'AP6  ',
                         'AP6PN',
                         'AP6PT',
                         'AP7  ',
                         'AP8  ',
                         'AP840',
                         'AP841',
                         'AP842',
                         'AP844',
                         'AP845',
                         'AP846',
                         'AP847',
                         'AP851',
                         'AP858',
                         'AP859',
                         'NP10 ',
                         'NP11 ',
                         'NP12 ',
                         'NP13 ',
                         'NP14 ',
                         'NP15 ',
                         'NP16 ',
                         'NP17 ',
                         'NP18 ',
                         'NP19 ',
                         'NP2  ',
                         'NP20 ',
                         'NP21 ',
                         'NP28 ',
                         'NP3  ',
                         'NP34 ',
                         'NP35 ',
                         'NP36 ',
                         'NP4  ',
                         'NP41 ',
                         'NP42 ',
                         'NP43 ',
                         'NP44 ',
                         'NP45 ',
                         'NP46 ',
                         'NP47 ',
                         'NP48 ',
                         'NP49 ',
                         'NP5  ',
                         'NP6  ',
                         'NP7  ',
                         'NP8  ',
                         'NP840',
                         'NP841',
                         'NP842',
                         'NP843',
                         'NP844',
                         'NP845',
                         'NP846',
                         'NP847',
                         'NP851',
                         'NP857',
                         'NP858',
                         'NP859',
                         'NP860')
  AND "L16T3"."MHA" IN ('11MW ',
                        '11R1H',
                        '11R1N',
                        '11R1T',
                        '11RPH',
                        '11RPN',
                        '11RPT',
                        '12MW ',
                        '12R1H',
                        '12R1N',
                        '12R1T',
                        '12RPH',
                        '12RPN',
                        '12RPT',
                        '13R1 ',
                        '13R1H',
                        '13R1N',
                        '13R1T',
                        '13RPN',
                        '13RPT',
                        '14R1 ',
                        '14R1H',
                        '14R1N',
                        '14R1T',
                        '14RPH',
                        '14RPN',
                        '14RPT',
                        '14RS ',
                        '15R1H',
                        '15R1N',
                        '15R1T',
                        '15RPH',
                        '15RPN',
                        '15RPT',
                        '16R1H',
                        '16R1N',
                        '16R1T',
                        '16RPH',
                        '16RPN',
                        '16RPT',
                        '17R1H',
                        '17R1N',
                        '17R1T',
                        '17RPH',
                        '17RPN',
                        '17RPT')