SELECT DISTINCT "SQL1"."_DelDate" "C__DelDate",
                "SQL1"."_Ordern" "C__Ordern",
                "SQL1"."_Orderlines" "C__Orderlines",
                "SQL1"."_Ordern abzuglich CANCL" "C__Ordern_abzuglich_CANCL",
                "SQL1"."_Orderlines abzuglich CANCL" "C__Orderlines_abzuglich_CANCL",
                "SQL1"."_Orderlines LOOP 1" "C__Orderlines_LOOP_1",
                "SQL1"."_OL LOOP 1 [%]" "C__OL_LOOP_1____",
                "SQL1"."_Orderlines LOOP 2" "C__Orderlines_LOOP_2",
                "SQL1"."_OL LOOP 2 [%]" "C__OL_LOOP_2____",
                "SQL1"."_Orderlines LOOP 3" "C__Orderlines_LOOP_3",
                "SQL1"."_OL LOOP 3 [%]" "C__OL_LOOP_3____",
                "SQL1"."_Orderlines LOOP 4" "C__Orderlines_LOOP_4",
                "SQL1"."_OL LOOP 4 [%]" "C__OL_LOOP_4____",
                "SQL1"."_Orderlines LOOP 5" "C__Orderlines_LOOP_5",
                "SQL1"."_OL LOOP 5 [%]" "C__OL_LOOP_5____",
                "SQL1"."_Orderlines LOOP 6" "C__Orderlines_LOOP_6",
                "SQL1"."_OL LOOP 6 [%]" "C__OL_LOOP_6____",
                "SQL1"."_Orderlines Conventional" "C__Orderlines_Conventional",
                "SQL1"."_OL Conventional [%]" "C__OL_Conventional____"
FROM "SQL1"