SELECT "SQL6"."Closed Date" "Closed_Date",
       "SQL6"."ARTICLE" "ARTICLE",
       "SQL6"."SUPPLIER" "SUPPLIER",
       "SQL6"."CDC" "CDC",
       "SQL6"."ARTSUP" "ARTSUP",
       "SQL6"."Trigger" "Trigger6",
       "SQL6"."Pick Type" "Pick_Type",
       "SQL6"."Pallet ID" "Pallet_ID",
       "SQL6"."Qty" "Qty",
       "SQL6"."Pallet Qty" "Pallet_Qty",
       sum("SQL6"."Pallets") "Pallets",
       "SQL6"."Pallet Class" "Pallet_Class",
       "SQL6"."Article Volume" "Article_Volume",
       sum("SQL6"."Received Volume") "Received_Volume",
       sum(1) "Units"
FROM "SQL6"
GROUP BY "SQL6"."Closed Date",
         "SQL6"."ARTICLE",
         "SQL6"."SUPPLIER",
         "SQL6"."CDC",
         "SQL6"."ARTSUP",
         "SQL6"."Trigger",
         "SQL6"."Pick Type",
         "SQL6"."Pallet ID",
         "SQL6"."Qty",
         "SQL6"."Pallet Qty",
         "SQL6"."Pallet Class",
         "SQL6"."Article Volume"