/* user=Jhanvi Nandani reportPath= report= queryName=Requete1 REMOTE_ADDR= SERVER_NAME=cognosanalytics.apps.ikea.com requestID=M948yqvdG48Gjy42ljGvC9j8Mjqlj8wvwqwvqGhw */ SELECT "SHP_LAST_BU_ADDRESS"."CLU_CODE" AS "Last_Stop_BU_Code",
       "SHP_LAST_BU_ADDRESS"."CLUT_TYPE" AS "Last_Stop_BU_Type",
       "SHP_LAST_BU_ADDRESS"."GA_CODE_CTY" AS "Last_Country_Code",
       "CSM"."CNOR_BU_CODE" AS "Consignor_BU_Code",
       "SHP"."SHP_ID" AS "Shipment_Id",
       "CSM"."CSM_NO" AS "Consignment_Number",
       "SHP"."LAST_ARR_EST_DTIME" AS "Last_Estimated_Arrival_Date_Time",
       "CNEE_BUSINESS_UNIT0"."NAME" AS "Consignee_Name",
       SUM("CSM_LINE"."LINE_QTY") AS "Line_Quantity",
       "CSM_LINE"."ITEM_NAME" AS "Item_Name",
       "CSM_LINE"."ITEM_TYPE" AS "Item_Type",
       "CSM"."CNEE_BU_CODE" AS "Consignee_BU_Code",
       SUM(("CSM"."TOT_NET_VOL" / 1000) / 1000) AS "Total_Net_Volume",
       "SHP"."EVENT_NAME" AS "Event_Name1"
FROM "ODR_DELIVERY_PUB"."CSM" "CSM"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_LINE" "CSM_LINE" ON "CSM_LINE"."CSM_NO" = "CSM"."CSM_NO"
AND "CSM_LINE"."CSM_CRE_BU_CODE" = "CSM"."CSM_CRE_BU_CODE"
AND "CSM_LINE"."CSM_CRE_BU_TYPE" = "CSM"."CSM_CRE_BU_TYPE"
AND "CSM_LINE"."LATEST_UPDATE_TIMESTAMP" = "CSM"."LATEST_UPDATE_TIMESTAMP"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_SHP" "CSM_SHP" ON "CSM_SHP"."CSM_CRE_BU_CODE" = "CSM"."CSM_CRE_BU_CODE"
AND "CSM_SHP"."CSM_CRE_BU_TYPE" = "CSM"."CSM_CRE_BU_TYPE"
AND "CSM_SHP"."CSM_NO" = "CSM"."CSM_NO"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."SHP" "SHP" ON "SHP"."SHP_NO" = "CSM_SHP"."SHP_NO"
AND "SHP"."SHP_CRE_BU_CODE" = "CSM_SHP"."SHP_CRE_BU_CODE"
AND "SHP"."SHP_CRE_BU_TYPE" = "CSM_SHP"."SHP_CRE_BU_TYPE"
LEFT OUTER JOIN "ODR_COMMON_PUB"."BU_ADDRESS_ITM_VW" "SHP_LAST_BU_ADDRESS" ON "SHP_LAST_BU_ADDRESS"."CLUT_TYPE" = "SHP"."LAST_STOP_BU_TYPE"
AND "SHP_LAST_BU_ADDRESS"."CLU_CODE" = "SHP"."LAST_STOP_BU_CODE"
AND "SHP_LAST_BU_ADDRESS"."SEQ_NO" = "SHP"."LAST_STOP_BU_SEQ"
LEFT OUTER JOIN "CNEE_BUSINESS_UNIT0" ON "CNEE_BUSINESS_UNIT0"."CLUT_TYPE" = "CSM"."CNEE_BU_TYPE"
AND "CNEE_BUSINESS_UNIT0"."CLU_CODE" = "CSM"."CNEE_BU_CODE"
AND "CNEE_BUSINESS_UNIT0"."SEQ_NO" = "CSM"."CNEE_BU_SEQ"
WHERE "SHP_LAST_BU_ADDRESS"."CLUT_TYPE" IN ('CDC')
  AND "SHP_LAST_BU_ADDRESS"."GA_CODE_CTY" IN ('FR')
  AND "SHP_LAST_BU_ADDRESS"."CLU_CODE" IN ('418')
  AND "CSM"."CNOR_BU_CODE" IN ('17198')
  AND "CSM_LINE"."ITEM_TYPE" IN ('ADS')
  AND "SHP"."LAST_ARR_EST_DTIME" > {ts '2022-12-12 00:00:00'}
  AND NOT ("CSM_LINE"."ITEM_NAME" IN ('SIDE PANELS'))
  AND NOT ("CSM_LINE"."ITEM_NAME" IN ('SIDE PANEL MINI'))
  AND NOT ("SHP"."EVENT_NAME" IN ('Arrival, completed - Shipment arrived (SHP) '))
GROUP BY "SHP_LAST_BU_ADDRESS"."CLU_CODE",
         "SHP_LAST_BU_ADDRESS"."CLUT_TYPE",
         "SHP_LAST_BU_ADDRESS"."GA_CODE_CTY",
         "CSM"."CNOR_BU_CODE",
         "SHP"."SHP_ID",
         "CSM"."CSM_NO",
         "SHP"."LAST_ARR_EST_DTIME",
         "CNEE_BUSINESS_UNIT0"."NAME",
         "CSM_LINE"."ITEM_NAME",
         "CSM_LINE"."ITEM_TYPE",
         "CSM"."CNEE_BU_CODE",
         "SHP"."EVENT_NAME"