SELECT "SQL1"."SHORTR08" "SHORTR08",
       "SQL1"."CDC" "CDC",
       "SQL1"."Sales Order #" "Sales_Order__",
       "SQL1"."Astro Order #" "Astro_Order__",
       "SQL1"."Closed Date" "Closed_Date",
       "SQL1"."Required Dispatch Date" "Required_Dispatch_Date",
       "SQL1"."Planned Dispatch Date" "Planned_Dispatch_Date",
       "SQL1"."Route Name" "Route_Name",
       "SQL1"."Flow" "Flow",
       "SQL1"."Receiver" "Receiver",
       "SQL1"."STATUS" "STATUS",
       "SQL1"."SHIPMENT_STATUS" "SHIPMENT_STATUS",
       sum("SQL1"."On Time") "On_Time",
       sum("SQL1"."Late") "Late",
       sum("SQL1"."TOTALORDERS") "TOTALORDERS",
       sum("SQL1"."On Time")/nullif(sum("SQL1"."TOTALORDERS"), 0) "On_Time__"
FROM "SQL1"
GROUP BY "SQL1"."SHORTR08",
         "SQL1"."CDC",
         "SQL1"."Sales Order #",
         "SQL1"."Astro Order #",
         "SQL1"."Closed Date",
         "SQL1"."Required Dispatch Date",
         "SQL1"."Planned Dispatch Date",
         "SQL1"."Route Name",
         "SQL1"."Flow",
         "SQL1"."Receiver",
         "SQL1"."STATUS",
         "SQL1"."SHIPMENT_STATUS"