/* user=Jhanvi Nandani reportPath= report= queryName=GeminiInbound_LW REMOTE_ADDR= SERVER_NAME=cognosanalytics.apps.ikea.com requestID=ydlq4G8q8dwvdjlv94ywlj22s8s4GvjsG4jqlssC */ SELECT DISTINCT "SQL9"."Inbound Units Sum" AS "Inbound_Units_Sum",
                "SQL9"."StUnits" AS "StUnits",
                "SQL9"."Pallets" AS "Pallets",
                "SQL9"."Total Volume" AS "Total_Volume",
                "SQL9"."Qty" AS "Qty",
                "SQL9"."Unit Volume" AS "Unit_Volume",
                "SQL9"."S.Line Type" AS "S_Line_Type",
                "SQL9"."Pallet ID" AS "Pallet_ID",
                "SQL9"."DC" AS "DC",
                "SQL9"."Art-Sup" AS "Art_Sup",
                "SQL9"."Supplier" AS "Supplier",
                "SQL9"."Article" AS "Article",
                "SQL9"."Consignment" AS "Consignment",
                "SQL9"."Shipment #" AS "Shipment__",
                "SQL9"."Unit Type" AS "Unit_Type",
                "SQL9"."Unit Size" AS "Unit_Size",
                "SQL9"."LU ID" AS "LU_ID",
                "SQL9"."Close Week" AS "Close_Week",
                "SQL9"."Close Date" AS "Close_Date"
FROM "SQL9"