/* user=Piratla Manikanta reportPath= report= queryName=Requete1 REMOTE_ADDR= SERVER_NAME=cognosanalytics.apps.ikea.com requestID=svMCC9C8Gshls2wGMMC8lyhChjGlydy9qvhGvCdy */ SELECT DISTINCT "Code_SQL1"."Date" AS "Date0",
                "Code_SQL1"."_Entrees totales" AS "C_Entrees_totales",
                "Code_SQL1"."_Entrees Conv" AS "C_Entrees_Conv",
                "Code_SQL1"."_Entrees Silo" AS "C_Entrees_Silo",
                "Code_SQL1"."_Sorties transit inclus" AS "C5",
                "Code_SQL1"."_Sorties Conv" AS "C_Sorties_Conv",
                "Code_SQL1"."_Sorties Silo" AS "C_Sorties_Silo",
                "Code_SQL1"."_Entrees Deep Stack" AS "C8",
                "Code_SQL1"."_Entrees XBlock" AS "C_Entrees_XBlock",
                "Code_SQL1"."_Entrees XBlock Frigo" AS "C10",
                "Code_SQL1"."_Entrees Xdock" AS "C_Entrees_Xdock",
                "Code_SQL1"."_Entrees B2" AS "C_Entrees_B2",
                "Code_SQL1"."_Entrees R2" AS "C_Entrees_R2",
                "Code_SQL1"."_Sorties Deep Stack" AS "C14",
                "Code_SQL1"."_Sorties XBlock" AS "C_Sorties_XBlock",
                "Code_SQL1"."_Sorties Xdock" AS "C_Sorties_Xdock",
                "Code_SQL1"."_Sorties B2" AS "C_Sorties_B2",
                "Code_SQL1"."_Sorties R2" AS "C_Sorties_R2",
                "Code_SQL1"."_Sorties XBlock Frigo" AS "C19"
FROM "Code_SQL1"