SELECT DISTINCT "SQL1"."Start Date" "Start_Date",
                "SQL1"."Closed Date" "Closed_Date",
                "SQL1"."Close Week" "Close_Week",
                "SQL1"."Elapsed Hours" "Elapsed_Hours",
                "SQL1"."Elapsed Hours Rounded" "Elapsed_Hours_Rounded",
                "SQL1"."Elapsed Minutes Rounded" "Elapsed_Minutes_Rounded",
                "SQL1"."Elapsed Days Rounded" "Elapsed_Days_Rounded",
                "SQL1"."Advised Date" "Advised_Date",
                "SQL1"."Receiving Status" "Receiving_Status",
                "SQL1"."Short G30" "Short_G30",
                "SQL1"."Shipment #" "Shipment__",
                "SQL1"."DELID" "DELID",
                "SQL1"."Short G36" "Short_G36",
                "SQL1"."SLTYPE" "SLTYPE",
                "SQL1"."ARTICLE" "ARTICLE",
                "SQL1"."SUPPLIER" "SUPPLIER",
                "SQL1"."CDC" "CDC",
                "SQL1"."ARTSUP" "ARTSUP",
                "SQL1"."Pallet ID" "Pallet_ID",
                "SQL1"."Buffer MHA" "Buffer_MHA",
                "SQL1"."Buff MHA" "Buff_MHA",
                "SQL1"."Transport ID" "Transport_ID",
                "SQL1"."Qty" "Qty",
                "SQL1"."Pallet Qty" "Pallet_Qty",
                "SQL1"."BUTYPECR" "BUTYPECR",
                "SQL1"."Pallets" "Pallets",
                "SQL1"."Pallet Class" "Pallet_Class",
                "SQL1"."Article Volume" "Article_Volume",
                "SQL1"."Received Volume" "Received_Volume",
                "SQL1"."SHPMENTSUM" "SHPMENTSUM"
FROM "SQL1"