SELECT to_char("OUT_MERGE"."DATE0", 'yyyy-MM-dd') AS "DATE0",
       "OUT_MERGE"."LDCT" AS "LDCT",
       EXTRACT(MONTH
               FROM "OUT_MERGE"."DATE0") AS "MONTH0",
       "OUT_MERGE"."OUT_PROF" AS "OUT_PROF",
       "OUT_MERGE"."OUT_SILO" AS "OUT_SILO",
       "OUT_MERGE"."OUT_PROF" + "OUT_MERGE"."OUT_SILO" AS "OUT_TOTAL",
       SUM("INB_MERGE"."INB_SILO") AS "INB_SILO",
       "INB_MERGE"."INB_PROF" AS "INB_PROF",
       SUM("INB_MERGE"."INB_SILO") + MIN("INB_MERGE"."INB_PROF") AS "INB_TOTAL"
FROM "OUT_MERGE"
INNER JOIN "INB_MERGE" ON "OUT_MERGE"."DATE0" = "INB_MERGE"."DATE0"
AND "OUT_MERGE"."LDCT" = "INB_MERGE"."LDCT"
GROUP BY to_char("OUT_MERGE"."DATE0", 'yyyy-MM-dd'),
         "OUT_MERGE"."LDCT",
         EXTRACT(MONTH
                 FROM "OUT_MERGE"."DATE0"),
         "OUT_MERGE"."OUT_PROF",
         "OUT_MERGE"."OUT_SILO",
         "OUT_MERGE"."OUT_PROF" + "OUT_MERGE"."OUT_SILO",
         "INB_MERGE"."INB_PROF"