SELECT DISTINCT "SQL1"."STATDATE" "STATDATE",
                "SQL1"."ORDNO" "ORDNO",
                "SQL1"."LSC Nummer" "LSC_Nummer",
                "SQL1"."NOORDL" "NOORDL",
                "SQL1"."EORDERID" "EORDERID",
                "SQL1"."PICKWGHT" "PICKWGHT",
                "SQL1"."PICKVOL" "PICKVOL",
                "SQL1"." Regdate Order" "C__Regdate_Order",
                "SQL1"."ORDLINE" "ORDLINE",
                "SQL1"."SHORTL62" "SHORTL62",
                "SQL1"."PARTNO" "PARTNO",
                "SQL1"."PARTREV" "PARTREV",
                "SQL1"."OL Statusdate" "OL_Statusdate",
                "SQL1"."REQQUANT" "REQQUANT",
                "SQL1"."CALCWGHT" "CALCWGHT",
                "SQL1"."CALCVOL" "CALCVOL",
                "SQL1"."DELQUANT" "DELQUANT",
                "SQL1"."DELWGHT" "DELWGHT",
                "SQL1"."DELVOL" "DELVOL",
                "SQL1"."PMHA" "PMHA",
                "SQL1"."WMHA" "WMHA",
                "SQL1"."CQUANT" "CQUANT",
                "SQL1"."SUVOL" "SUVOL",
                "SQL1"."SUWGHT" "SUWGHT",
                "SQL1"."SULENGTH" "SULENGTH",
                "SQL1"."SUWIDTH" "SUWIDTH",
                "SQL1"."SUHEIGHT" "SUHEIGHT",
                "SQL1"."HULENGTH" "HULENGTH",
                "SQL1"."HUWIDTH" "HUWIDTH",
                "SQL1"."HUHEIGHT" "HUHEIGHT",
                "SQL1"."HUQTY" "HUQTY",
                "SQL1"."WLDCT" "WLDCT",
                "SQL1"."FIRECODE" "FIRECODE",
                "SQL1"."PARTDSC1" "PARTDSC1",
                "SQL1"."ECARRNO" "ECARRNO",
                "SQL1"."WEIGHT" "WEIGHT",
                "SQL1"."CARRVOL" "CARRVOL",
                "SQL1"."OCARRTYP" "OCARRTYP"
FROM "SQL1"