SELECT "SQL4"."Closed Date" "Closed_Date",
       "SQL4"."Advised Date" "Advised_Date",
       "SQL4"."Receiving Status" "Receiving_Status",
       "SQL4"."SHORTG30" "SHORTG30",
       "SQL4"."Shipment #" "Shipment__",
       "SQL4"."DELID" "DELID",
       "SQL4"."SHORTG36" "SHORTG36",
       "SQL4"."SLTYPE" "SLTYPE",
       "SQL4"."ARTICLE" "ARTICLE",
       "SQL4"."SUPPLIER" "SUPPLIER",
       "SQL4"."DC" "DC",
       "SQL4"."ARTSUP" "ARTSUP",
       "SQL4"."Pallet ID" "Pallet_ID",
       "SQL4"."Transport ID" "Transport_ID",
       "SQL4"."Qty" "Qty",
       "SQL4"."Pallet Qty" "Pallet_Qty",
       "SQL4"."Pallet Class" "Pallet_Class",
       "SQL4"."BUTYPECR" "BUTYPECR",
       sum("SQL4"."Pallets") "Pallets",
       sum("SQL4"."Article Volume") "Article_Volume",
       sum("SQL4"."Received Volume") "Received_Volume",
       sum("SQL4"."SHPMENTSUM") "Shipments"
FROM "SQL4"
GROUP BY "SQL4"."Closed Date",
         "SQL4"."Advised Date",
         "SQL4"."Receiving Status",
         "SQL4"."SHORTG30",
         "SQL4"."Shipment #",
         "SQL4"."DELID",
         "SQL4"."SHORTG36",
         "SQL4"."SLTYPE",
         "SQL4"."ARTICLE",
         "SQL4"."SUPPLIER",
         "SQL4"."DC",
         "SQL4"."ARTSUP",
         "SQL4"."Pallet ID",
         "SQL4"."Transport ID",
         "SQL4"."Qty",
         "SQL4"."Pallet Qty",
         "SQL4"."Pallet Class",
         "SQL4"."BUTYPECR"