
SELECT DISTINCT "IN_LOADING_UNIT_TRIP"."BU_TYPE_DT" AS "BU_TYPE_DT",
                "IN_LOADING_UNIT_TRIP"."BU_CODE_DT" AS "BU_CODE_DT",
                "IN_LOADING_UNIT_TRIP"."LU_ID" AS "LU_ID",
                "IN_LOADING_UNIT_TRIP"."BU_TYPE_START" AS "BU_TYPE_START",
                "IN_LOADING_UNIT_TRIP"."BU_CODE_START" AS "BU_CODE_START",
                "IN_LOADING_UNIT_TRIP"."BU_TYPE_END" AS "BU_TYPE_END",
                "IN_LOADING_UNIT_TRIP"."BU_CODE_END" AS "BU_CODE_END",
                "IN_LOADING_UNIT_TRIP"."ACT_START_DATE" AS "ACT_START_DATE",
                "IN_LOADING_UNIT_TRIP"."ACT_END_DATE" AS "ACT_END_DATE",
                "IN_CONTAINER_TRIP"."COMMENTS" AS "COMMENTS",
                "IN_CONTAINER_TRIP"."ACT_UNLOAD_FINISH_TIME" AS "ACT_UNLOAD_FINISH_TIME",
                "IN_CONTAINER_TRIP"."ACT_UNLOAD_START_TIME" AS "ACT_UNLOAD_START_TIME",
                "IN_LOADING_UNIT_TRIP"."PLAN_END_DATE" AS "PLAN_END_DATE",
                "IN_CONTAINER_TRIP"."PLAN_UNLOAD_START_TIME" AS "PLAN_UNLOAD_START_TIME"
FROM "GEMINI"."IN_CONNECTED_CONSIGNMENT" "IN_CONNECTED_CONSIGNMENT"
INNER JOIN "GEMINI"."IN_LOADING_UNIT_TRIP" "IN_LOADING_UNIT_TRIP" ON "IN_CONNECTED_CONSIGNMENT"."SHP_NO" = "IN_LOADING_UNIT_TRIP"."SHP_NO"
AND "IN_CONNECTED_CONSIGNMENT"."BU_CODE_CRE_SHP" = "IN_LOADING_UNIT_TRIP"."BU_CODE_CRE_SHP"
AND "IN_CONNECTED_CONSIGNMENT"."BU_TYPE_CRE_SHP" = "IN_LOADING_UNIT_TRIP"."BU_TYPE_CRE_SHP"
AND "IN_CONNECTED_CONSIGNMENT"."BU_CODE_DT" = "IN_LOADING_UNIT_TRIP"."BU_CODE_DT"
AND "IN_CONNECTED_CONSIGNMENT"."BU_TYPE_DT" = "IN_LOADING_UNIT_TRIP"."BU_TYPE_DT"
AND "IN_CONNECTED_CONSIGNMENT"."LUTR_NO" = "IN_LOADING_UNIT_TRIP"."LUTR_NO"
INNER JOIN "GEMINI"."IN_CONTAINER_TRIP" "IN_CONTAINER_TRIP" ON "IN_CONTAINER_TRIP"."IN_CONT_NO" = "IN_CONNECTED_CONSIGNMENT"."IN_CONT_NO"
WHERE "IN_CONTAINER_TRIP"."ACT_UNLOAD_FINISH_TIME" IS NULL
  AND "IN_LOADING_UNIT_TRIP"."BU_TYPE_DT" IN ('DT')
  AND "IN_CONTAINER_TRIP"."COMMENTS" LIKE '%RED ALERT%'
  AND ("IN_LOADING_UNIT_TRIP"."ACT_END_DATE" > TRUNC(CURRENT_DATE) - 120
       OR "IN_LOADING_UNIT_TRIP"."ACT_END_DATE" IS NULL)