SELECT DISTINCT "SQL2"."Start Date" "Start_Date",
                "SQL2"."Closed Date" "Closed_Date",
                "SQL2"."Close Week" "Close_Week",
                "SQL2"."Elapsed Hours" "Elapsed_Hours",
                "SQL2"."Elapsed Hours Rounded" "Elapsed_Hours_Rounded",
                "SQL2"."Elapsed Minutes Rounded" "Elapsed_Minutes_Rounded",
                "SQL2"."Elapsed Days Rounded" "Elapsed_Days_Rounded",
                "SQL2"."Advised Date" "Advised_Date",
                "SQL2"."Receiving Status" "Receiving_Status",
                "SQL2"."Short G30" "Short_G30",
                "SQL2"."Shipment #" "Shipment__",
                "SQL2"."DELID" "DELID",
                "SQL2"."Short G36" "Short_G36",
                "SQL2"."SLTYPE" "SLTYPE",
                "SQL2"."ARTICLE" "ARTICLE",
                "SQL2"."SUPPLIER" "SUPPLIER",
                "SQL2"."CDC" "CDC",
                "SQL2"."ARTSUP" "ARTSUP",
                "SQL2"."Pallet ID" "Pallet_ID",
                "SQL2"."Buffer MHA" "Buffer_MHA",
                "SQL2"."Buff MHA" "Buff_MHA",
                "SQL2"."Transport ID" "Transport_ID",
                "SQL2"."Qty" "Qty",
                "SQL2"."Pallet Qty" "Pallet_Qty",
                "SQL2"."BUTYPECR" "BUTYPECR",
                "SQL2"."Pallets" "Pallets",
                "SQL2"."Pallet Class" "Pallet_Class",
                "SQL2"."LdCT" "LdCT",
                "SQL2"."Article Volume" "Article_Volume",
                "SQL2"."Received Volume" "Received_Volume",
                "SQL2"."SHPMENTSUM" "SHPMENTSUM"
FROM "SQL2"