SELECT "SQL2"."CDC" "CDC", 
       "SQL2"."Status Date" "Status_Date", 
       "SQL2"."Aging Hours" "Aging_Hours", 
       "SQL2"."MHA" "MHA", 
       "SQL2"."Location" "Location", 
       "SQL2"."Package ID" "Package_ID", 
       "SQL2"."Article" "Article", 
       "SQL2"."Revision" "Revision", 
       "SQL2"."Qty" "Qty", 
       "SQL2"."Full / Partial" "Full___Partial", 
       "SQL2"."FPQ" "FPQ", 
       "SQL2"."Available" "Available", 
       "SQL2"."Block Code" "Block_Code", 
       "SQL2"."Reserved" "Reserved", 
       "SQL2"."To MHA" "To_MHA", 
       "SQL2"."LdCT" "LdCT", 
       "SQL2"."Pallet Class" "Pallet_Class", 
       "SQL2"."HFB" "HFB", 
       "SQL2"."HFB Definition" "HFB_Definition", 
       "SQL2"."Multi-box?" "Multi_box_", 
       "SQL2"."Num PCS" "Num_PCS", 
       "SQL2"."Unit Net Volume" "Unit_Net_Volume", 
       "SQL2"."Buffer MHA" "Buffer_MHA", 
       "SQL2"."Pick MHA" "Pick_MHA", 
       "SQL2"."Pick Zone" "Pick_Zone", 
       "SQL2"."Carrno" "Carrno", 
       "SQL2"."Short L62" "Short_L62", 
       "SQL2"."Days Aging" "Days_Aging", 
       sum("SQL2"."Net Volume") "Total_Net_Volume", 
       sum(1) "Total_Pallets", 
       sum(CASE 
               WHEN "SQL2"."Aging Hours">=24 THEN '1' 
               ELSE '0'
           END) "Pallets_Aging___24_H"
FROM "SQL2"
GROUP BY "SQL2"."CDC",
         "SQL2"."Status Date",
         "SQL2"."Aging Hours",
         "SQL2"."MHA",
         "SQL2"."Location",
         "SQL2"."Package ID",
         "SQL2"."Article",
         "SQL2"."Revision",
         "SQL2"."Qty",
         "SQL2"."Full / Partial",
         "SQL2"."FPQ",
         "SQL2"."Available",
         "SQL2"."Block Code",
         "SQL2"."Reserved",
         "SQL2"."To MHA",
         "SQL2"."LdCT",
         "SQL2"."Pallet Class",
         "SQL2"."HFB",
         "SQL2"."HFB Definition",
         "SQL2"."Multi-box?",
         "SQL2"."Num PCS",
         "SQL2"."Unit Net Volume",
         "SQL2"."Buffer MHA",
         "SQL2"."Pick MHA",
         "SQL2"."Pick Zone",
         "SQL2"."Carrno",
         "SQL2"."Short L62",
         "SQL2"."Days Aging"