SELECT TO_CHAR(AL1.UNL_DAY+1, 'IW') "Week#",
       AL2.BU_CODE_START,
       AL2.BU_TYPE_START,
       AL2.BU_CODE_END,
       AL2.BU_TYPE_END,
       AL2.SHP_NO,
       AL1.CSM_NO,
       AL2.PLD_START_DATE,
       AL2.ACT_START_DATE,
       AL2.PLD_END_DATE,
       AL2.ACT_END_DATE,
       AL1.UNL_DAY,
       AL1.CSM_VOL_NET_ACT,
       AL4.LU_ID
FROM OBIEE_NA.CONSIGNMENT AL1,
     CNS_DW.SHIPMENT_ROUTE AL2,
     OBIEE_NA.CONNECTED_CSM AL3,
     CNS_DW.LOADING_UNIT_TRIP AL4
WHERE AL3.CSM_NO=AL1.CSM_NO
  AND AL3.BU_CODE_CRE_SHP=AL2.BU_CODE_CRE_SHP
  AND AL3.BU_TYPE_CRE_SHP=AL2.BU_TYPE_CRE_SHP
  AND AL3.SHP_NO=AL2.SHP_NO
  AND AL3.SHPR_NO=AL2.SHPR_NO
  AND AL1.BU_CODE_CRE=AL3.BU_CODE_CRE_CSM
  AND AL1.BU_TYPE_CRE=AL3.BU_TYPE_CRE_CSM
  AND AL4.BU_CODE_CRE_SHP=AL2.BU_CODE_CRE_SHP
  AND AL4.BU_TYPE_CRE_SHP=AL2.BU_TYPE_CRE_SHP
  AND AL4.SHP_NO=AL2.SHP_NO
  AND AL1.UNL_DAY IS NULL
  AND AL2.TRZ_CODE_END LIKE 'US%'
  AND AL2.BU_CODE_END='622'
  AND AL2.BU_TYPE_END='STO'