/* user=Piratla Manikanta reportPath= report= queryName=Query1 REMOTE_ADDR= SERVER_NAME=cognosanalytics.apps.ikea.com requestID=9yj982C4qClh4s29dMCjdM849hlyh9js4vdG4vdl */
SELECT "SHP"."SHP_ID",
       "SHP"."SHP_NO",
       "SHP"."FIRST_STOP_BU_CODE",
       "SHP"."FIRST_STOP_BU_TYPE",
       "SHP"."LAST_STOP_BU_CODE",
       "SHP"."LAST_STOP_BU_TYPE",
       "SHP"."LAST_ARR_PLAN_DTIME",
       "SHP"."LAST_ARR_EST_DTIME",
       "SHP"."LAST_ARR_ACT_DTIME",
       "SHP"."LAST_DEP_ACT_DTIME",
       "CSM"."CSM_ID",
       "CSM"."CSM_NO",
       "SHP_EV"."REC24_CODE",
       "SHP_EV"."SUB_CODE",
       "SHP"."SERV_PROV_NAME"
FROM "ODR_DELIVERY_PUB"."CSM" "CSM"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_SHP" "CSM_SHP" ON "CSM_SHP"."CSM_CRE_BU_CODE" = "CSM"."CSM_CRE_BU_CODE"
AND "CSM_SHP"."CSM_CRE_BU_TYPE" = "CSM"."CSM_CRE_BU_TYPE"
AND "CSM_SHP"."CSM_NO" = "CSM"."CSM_NO"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."SHP" "SHP" ON "SHP"."SHP_NO" = "CSM_SHP"."SHP_NO"
AND "SHP"."SHP_CRE_BU_CODE" = "CSM_SHP"."SHP_CRE_BU_CODE"
AND "SHP"."SHP_CRE_BU_TYPE" = "CSM_SHP"."SHP_CRE_BU_TYPE"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."SHP_EV" "SHP_EV" ON "SHP_EV"."SHP_NO" = "SHP"."SHP_NO"
AND "SHP_EV"."LATEST_UPDATE_TIMESTAMP" = "SHP"."LATEST_UPDATE_TIMESTAMP"
AND "SHP_EV"."SHP_CRE_BU_CODE" = "SHP"."SHP_CRE_BU_CODE"
AND "SHP_EV"."SHP_CRE_BU_TYPE" = "SHP"."SHP_CRE_BU_TYPE"
WHERE "SHP_EV"."REC24_CODE" = '1'
  AND "SHP_EV"."SUB_CODE" = '1'
  AND "SHP"."LAST_DEP_ACT_DTIME" BETWEEN TIMESTAMP '2025-03-26 00:00:00+00:00' AND TIMESTAMP '2025-03-26 23:59:59.999000000+00:00'
  AND "SHP"."LAST_STOP_BU_CODE" = '063'
  AND "SHP"."LAST_STOP_BU_TYPE" = 'CDC'