SELECT DISTINCT "Offene_Orderlines_H1__Status_"."DelDate" "DelDate",
                "Offene_Orderlines_H1__Status_"."1 Received" "C_1_Received",
                "Offene_Orderlines_H1__Status_"."22 Planned" "C_22_Planned",
                "Offene_Orderlines_H1__Status_"."30 Box calculation" "C_30_Box_calculation",
                "Offene_Orderlines_H1__Status_"."2 Released" "C_2_Released",
                "Offene_Orderlines_H1__Status_"."4 Being picked" "C_4_Being_picked",
                "Offene_Orderlines_H1__Status_"."5 Picked" "C_5_Picked",
                "Offene_Orderlines_H1__Status_"."7 Packed" "C_7_Packed",
                "Offene_Orderlines_H1__Status_"."Summe not Delivered (1-8)" "Summe_not_Delivered__1_8_",
                "Offene_Orderlines_H1__Status_"."9 Delivered" "C_9_Delivered",
                "Offene_Orderlines_H1__Status_"."Orderlines ges (1-9)" "Orderlines_ges__1_9_",
                "Offene_Orderlines_H1__Status_"."DelDate DHL" "DelDate_DHL",
                "Offene_Orderlines_H1__Status_"."1 Received DHL" "C_1_Received_DHL",
                "Offene_Orderlines_H1__Status_"."22 Planned DHL" "C_22_Planned_DHL",
                "Offene_Orderlines_H1__Status_"."30 Box calculation DHL" "C_30_Box_calculation_DHL",
                "Offene_Orderlines_H1__Status_"."2 Released DHL" "C_2_Released_DHL",
                "Offene_Orderlines_H1__Status_"."4 Being picked DHL" "C_4_Being_picked_DHL",
                "Offene_Orderlines_H1__Status_"."5 Picked DHL" "C_5_Picked_DHL",
                "Offene_Orderlines_H1__Status_"."7 Packed DHL" "C_7_Packed_DHL",
                "Offene_Orderlines_H1__Status_"."Summe not Delivered (1-8) DHL" "Summe_not_Delivered__1_8__DHL",
                "Offene_Orderlines_H1__Status_"."9 Delivered DHL" "C_9_Delivered_DHL",
                "Offene_Orderlines_H1__Status_"."Orderlines ges (1-9) DHL" "Orderlines_ges__1_9__DHL",
                "Offene_Orderlines_H1__Status_"."DelDate HERMES" "DelDate_HERMES",
                "Offene_Orderlines_H1__Status_"."1 Received HERMES" "C_1_Received_HERMES",
                "Offene_Orderlines_H1__Status_"."22 Planned HERMES" "C_22_Planned_HERMES",
                "Offene_Orderlines_H1__Status_"."30 Box calculation HERMES" "C_30_Box_calculation_HERMES",
                "Offene_Orderlines_H1__Status_"."2 Released HERMES" "C_2_Released_HERMES",
                "Offene_Orderlines_H1__Status_"."4 Being picked HERMES" "C_4_Being_picked_HERMES",
                "Offene_Orderlines_H1__Status_"."5 Picked HERMES" "C_5_Picked_HERMES",
                "Offene_Orderlines_H1__Status_"."7 Packed HERMES" "C_7_Packed_HERMES",
                "Offene_Orderlines_H1__Status_"."Summe not Delivered (1-8) HER" "Summe_not_Delivered__1_8__HER",
                "Offene_Orderlines_H1__Status_"."9 Delivered HERMES" "C_9_Delivered_HERMES",
                "Offene_Orderlines_H1__Status_"."Orderlines ges (1-9) HERMES" "Orderlines_ges__1_9__HERMES"
FROM "Offene_Orderlines_H1__Status_"