/* user=Jhanvi Nandani reportPath= report= queryName=OutCMR REMOTE_ADDR= SERVER_NAME=cognosanalytics.apps.ikea.com requestID=CywMsh44jssG8wChqG49y9Mhq8q2vhC4q9wydsj9 */ SELECT "SQL1"."Dispatch Date" AS "Dispatch_Date",
       "SQL1"."Dispatch Week" AS "Dispatch_Week",
       "SQL1"."Order Date" AS "Order_Date",
       "SQL1"."Order Week" AS "Order_Week",
       "SQL1"."DC" AS "DC",
       "SQL1"."Receiver" AS "Receiver",
       "SQL1"."Rec Name" AS "Rec_Name",
       "SQL1"."CTY_CODE" AS "CTY_CODE",
       "SQL1"."DomExp" AS "Flow",
       "SQL1"."Stock Switch" AS "Stock_Switch",
       "SQL1"."SHP_NO" AS "SHP_NO",
       "SQL1"."ShortR08" AS "ShortR08",
       "SQL1"."Consignment #" AS "Consignment__",
       "SQL1"."Gemini Order #" AS "Gemini_Order__",
       "SQL1"."Astro Order #" AS "Astro_Order__",
       "SQL1"."OP_ORD_ID" AS "OP_ORD_ID",
       "SQL1"."ORDER_TYPE" AS "ORDER_TYPE",
       "SQL1"."Order Type" AS "Order_Type18",
       "SQL1"."Order Line Type" AS "Order_Line_Type",
       "SQL1"."Pick Type MIP" AS "Pick_Type_MIP",
       "SQL1"."PALLET_ID" AS "PALLET_ID",
       "SQL1"."Article" AS "Article",
       "SQL1"."ITEM_TYPE" AS "ITEM_TYPE",
       "SQL1"."Supplier" AS "Supplier",
       "SQL1"."ARTSUP" AS "ARTSUP",
       "SQL1"."BU_TYPE_SUP" AS "BU_TYPE_SUP",
       "SQL1"."PA_NO" AS "PA_NO",
       "SQL1"."HFB" AS "HFB",
       "SQL1"."ITEM_SUP_DWP_ACT" AS "ITEM_SUP_DWP_ACT",
       "SQL1"."ITEM_SUP_DWP_ACT_UL" AS "C30",
       "SQL1"."ITEM_SUP_WS_FYT" AS "ITEM_SUP_WS_FYT",
       "SQL1"."Unit Volume" AS "Unit_Volume",
       "SQL1"."Line17 Price" AS "Line17_Price",
       "SQL1"."Tertial Pricing" AS "Tertial_Pricing",
       "SQL1"."Disp Qty" AS "Disp_Qty",
       SUM("SQL1"."Volume") AS "Volume",
       SUM("SQL1"."Price") AS "Price",
       SUM("SQL1"."ORDERSUM") AS "Orders",
       SUM("SQL1"."PALLETSUM") AS "Pallets",
       SUM("SQL1"."SHIPMENTSUM") AS "Shipments_as_Sum"
FROM "SQL1"
GROUP BY "SQL1"."Dispatch Date",
         "SQL1"."Dispatch Week",
         "SQL1"."Order Date",
         "SQL1"."Order Week",
         "SQL1"."DC",
         "SQL1"."Receiver",
         "SQL1"."Rec Name",
         "SQL1"."CTY_CODE",
         "SQL1"."DomExp",
         "SQL1"."Stock Switch",
         "SQL1"."SHP_NO",
         "SQL1"."ShortR08",
         "SQL1"."Consignment #",
         "SQL1"."Gemini Order #",
         "SQL1"."Astro Order #",
         "SQL1"."OP_ORD_ID",
         "SQL1"."ORDER_TYPE",
         "SQL1"."Order Type",
         "SQL1"."Order Line Type",
         "SQL1"."Pick Type MIP",
         "SQL1"."PALLET_ID",
         "SQL1"."Article",
         "SQL1"."ITEM_TYPE",
         "SQL1"."Supplier",
         "SQL1"."ARTSUP",
         "SQL1"."BU_TYPE_SUP",
         "SQL1"."PA_NO",
         "SQL1"."HFB",
         "SQL1"."ITEM_SUP_DWP_ACT",
         "SQL1"."ITEM_SUP_DWP_ACT_UL",
         "SQL1"."ITEM_SUP_WS_FYT",
         "SQL1"."Unit Volume",
         "SQL1"."Line17 Price",
         "SQL1"."Tertial Pricing",
         "SQL1"."Disp Qty"