SELECT DISTINCT "SQL1"."UPDDATE" "UPDDATE",
                "SQL1"."ROUTENO" "ROUTENO",
                "SQL1"."OCARRNO" "OCARRNO",
                "SQL1"."SHORTL62" "SHORTL62",
                "SQL1"."_Auto/Conv." "C__Auto_Conv_",
                "SQL1"."ECARRNO" "ECARRNO",
                "SQL1"."SHORTO06" "SHORTO06",
                "SQL1"."ORDNO" "ORDNO",
                "SQL1"."SHORTO08" "SHORTO08",
                "SQL1"."PARTNO" "PARTNO",
                "SQL1"."PARTREV" "PARTREV",
                "SQL1"."ORDLINE" "ORDLINE",
                "SQL1"."EORDERID" "EORDERID",
                "SQL1"."WORDREF" "WORDREF",
                "SQL1"."NOORDL" "NOORDL",
                "SQL1"."REGDATE" "REGDATE",
                "SQL1"."SHORTO42" "SHORTO42",
                "SQL1"."OCARRTYP" "OCARRTYP",
                "SQL1"."_Del. Date" "C__Del__Date",
                "SQL1"."_Pick from" "C__Pick_from",
                "SQL1"."PMHA" "PMHA",
                "SQL1"."OCQUANT" "OCQUANT",
                "SQL1"."LUID" "LUID",
                "SQL1"."_Volumen" "C__Volumen",
                "SQL1"."_Weight" "C__Weight",
                "SQL1"."_Del Date" "C__Del_Date",
                "SQL1"."_In Time?" "C__In_Time_",
                "SQL1"."_Weight Order" "C__Weight_Order",
                "SQL1"."_Vol. Order" "C__Vol__Order"
FROM "SQL1"