
SELECT "SHP"."SHP_ID" AS "Shipment_Id",
       "CSM"."CSM_ID" AS "Consignment_Id",
       "SHP_LAST_BU_ADDRESS"."CLU_CODE" AS "Last_Stop_BU_Code",
       "SHP_LAST_BU_ADDRESS"."CLUT_TYPE" AS "Last_Stop_BU_Type",
       "CSM_LINE"."ORD_ORDL_INT" AS "Internal_Order_Line1",
       "SHP"."LAST_ARR_PLAN_DTIME" AS "Last_Planned_Arrival_Date_Time",
       "SHP"."EQUIP_ISO_CODE" AS "Equipment_ISO_Code",
       "CSM"."CNOR_BU_CODE" AS "Expediteur",
       "SHP"."LAST_STOP_BU_CODE" AS "Destinataire",
       "CSM_LINE"."DWP_ITEM_NO" AS "DWP_Item_Number",
       "CSM_LINE"."DWP_SUP_BU_CODE" AS "DWP_Supplier_BU_Code",
       SUM("CSM_LINE"."LINE_QTY") AS "Line_Quantity",
       "CSM_LINE"."ITEM_TYPE" AS "Item_Type",
       "CSM_LINE"."DSP_UNIT_TYPE" AS "Dispatch_Unit_Type",
       SUM("CSM_EV_72_L"."RCV_UNDAM_QTY" + "CSM_EV_72_L"."RCV_DAM_QTY") AS "Item_Quantity_Unload",
       SUM("CSM_EV_48_1_L"."LOAD_QTY") AS "Item_Quantity_Dispatched",
       "CSM"."FLOW_TYPE" AS "Flow_Type",
       SUM("ITEM_ATTRIBUTE"."AVG_MP_QTY") AS "Avg_Multi_Pack_Quantity",
       SUM("ITEM_ATTRIBUTE"."AVG_UL_QTY") AS "Avg_Unit_Load_Quantity",
       SUM("CSM"."TOT_PACK_NOF") AS "Total_Number_Of_Packages",
       "SHP"."FLOW_TYPE" AS "Flow_Type1",
       SUM("CSM"."TOT_DSP_PACK_NOF") AS "Total_Dispatched_Number_Of_Packages",
       "CSM"."CNOR_BU_SEQ" AS "Sequence0",
       "ITEM_ATTRIBUTE"."HFB_NAME_EN" AS "HFB_Name"
FROM "ODR_DELIVERY_PUB"."CSM" "CSM"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_LINE" "CSM_LINE" ON "CSM_LINE"."CSM_NO" = "CSM"."CSM_NO"
AND "CSM_LINE"."CSM_CRE_BU_CODE" = "CSM"."CSM_CRE_BU_CODE"
AND "CSM_LINE"."CSM_CRE_BU_TYPE" = "CSM"."CSM_CRE_BU_TYPE"
AND "CSM_LINE"."LATEST_UPDATE_TIMESTAMP" = "CSM"."LATEST_UPDATE_TIMESTAMP"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_EV_72_L" "CSM_EV_72_L" ON "CSM_EV_72_L"."CSM_CRE_BU_CODE" = "CSM_LINE"."CSM_CRE_BU_CODE"
AND "CSM_EV_72_L"."CSM_CRE_BU_TYPE" = "CSM_LINE"."CSM_CRE_BU_TYPE"
AND "CSM_EV_72_L"."CSM_NO" = "CSM_LINE"."CSM_NO"
AND "CSM_EV_72_L"."SEQ" = "CSM_LINE"."SEQ"
AND "CSM_EV_72_L"."ITEM_NO" = "CSM_LINE"."ITEM_NO"
AND "CSM_EV_72_L"."LATEST_UPDATE_TIMESTAMP" = "CSM_LINE"."LATEST_UPDATE_TIMESTAMP"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_EV_48_1_L" "CSM_EV_48_1_L" ON "CSM_EV_48_1_L"."CSM_CRE_BU_CODE" = "CSM_LINE"."CSM_CRE_BU_CODE"
AND "CSM_EV_48_1_L"."CSM_CRE_BU_TYPE" = "CSM_LINE"."CSM_CRE_BU_TYPE"
AND "CSM_EV_48_1_L"."CSM_NO" = "CSM_LINE"."CSM_NO"
AND "CSM_EV_48_1_L"."SEQ" = "CSM_LINE"."SEQ"
AND "CSM_EV_48_1_L"."ITEM_NO" = "CSM_LINE"."ITEM_NO"
AND "CSM_EV_48_1_L"."LATEST_UPDATE_TIMESTAMP" = "CSM_LINE"."LATEST_UPDATE_TIMESTAMP"
LEFT OUTER JOIN "ODR_COMMON_PUB"."ITEM_ATTRIBUTE" "ITEM_ATTRIBUTE" ON "ITEM_ATTRIBUTE"."ITEM_NO" = "CSM_LINE"."ITEM_NO"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."CSM_SHP" "CSM_SHP" ON "CSM_SHP"."CSM_CRE_BU_CODE" = "CSM"."CSM_CRE_BU_CODE"
AND "CSM_SHP"."CSM_CRE_BU_TYPE" = "CSM"."CSM_CRE_BU_TYPE"
AND "CSM_SHP"."CSM_NO" = "CSM"."CSM_NO"
LEFT OUTER JOIN "ODR_DELIVERY_PUB"."SHP" "SHP" ON "SHP"."SHP_NO" = "CSM_SHP"."SHP_NO"
AND "SHP"."SHP_CRE_BU_CODE" = "CSM_SHP"."SHP_CRE_BU_CODE"
AND "SHP"."SHP_CRE_BU_TYPE" = "CSM_SHP"."SHP_CRE_BU_TYPE"
LEFT OUTER JOIN "ODR_COMMON_PUB"."BU_ADDRESS_ITM_VW" "SHP_LAST_BU_ADDRESS" ON "SHP_LAST_BU_ADDRESS"."CLUT_TYPE" = "SHP"."LAST_STOP_BU_TYPE"
AND "SHP_LAST_BU_ADDRESS"."CLU_CODE" = "SHP"."LAST_STOP_BU_CODE"
AND "SHP_LAST_BU_ADDRESS"."SEQ_NO" = "SHP"."LAST_STOP_BU_SEQ"
WHERE "SHP_LAST_BU_ADDRESS"."CLUT_TYPE" IN ('CDC')
  AND "SHP_LAST_BU_ADDRESS"."CLU_CODE" IN ('005')
  AND "SHP"."LAST_ARR_PLAN_DTIME" BETWEEN TIMESTAMP '2025-03-17 00:00:00+00:00' AND TIMESTAMP '2025-03-24 23:59:59.999000000+00:00'
GROUP BY "SHP"."SHP_ID",
         "CSM"."CSM_ID",
         "SHP_LAST_BU_ADDRESS"."CLU_CODE",
         "SHP_LAST_BU_ADDRESS"."CLUT_TYPE",
         "CSM_LINE"."ORD_ORDL_INT",
         "SHP"."LAST_ARR_PLAN_DTIME",
         "SHP"."EQUIP_ISO_CODE",
         "CSM"."CNOR_BU_CODE",
         "SHP"."LAST_STOP_BU_CODE",
         "CSM_LINE"."DWP_ITEM_NO",
         "CSM_LINE"."DWP_SUP_BU_CODE",
         "CSM_LINE"."ITEM_TYPE",
         "CSM_LINE"."DSP_UNIT_TYPE",
         "CSM"."FLOW_TYPE",
         "SHP"."FLOW_TYPE",
         "CSM"."CNOR_BU_SEQ",
         "ITEM_ATTRIBUTE"."HFB_NAME_EN"