SELECT "SQL1"."DATREG" "DATREG",
       "SQL1"."Date" "Date2",
       "SQL1"."Week" "Week",
       "SQL1"."CDC" "CDC",
       "SQL1"."Shift" "Shift",
       "SQL1"."Astro Order #" "Astro_Order__",
       "SQL1"."Short O08" "Short_O08",
       "SQL1"."ISOM Order #" "ISOM_Order__",
       "SQL1"."TrPac" "TrPac",
       "SQL1"."Article" "Article",
       "SQL1"."Supplier" "Supplier",
       "SQL1"."Short L62" "Short_L62",
       "SQL1"."Pick MHA" "Pick_MHA",
       "SQL1"."HFB" "HFB",
       "SQL1"."Short R08" "Short_R08",
       "SQL1"."Route Schedule" "Route_Schedule",
       "SQL1"."Plan Date" "Plan_Date",
       "SQL1"."Shipment #" "Shipment__",
       "SQL1"."Receiver" "Receiver",
       "SQL1"."Receiver #" "Receiver__",
       "SQL1"."Flow" "Flow",
       "SQL1"."Reason Code" "Reason_Code",
       "SQL1"."Reason" "Reason",
       "SQL1"."Reason Alt Desc" "Reason_Alt_Desc",
       "SQL1"."Cancelled By" "Cancelled_By",
       "SQL1"."Log ID (L16T3)" "Log_ID__L16T3_",
       sum("SQL1"."OrderLine Sum") "Order_Lines_Cancelled"
FROM "SQL1"
GROUP BY "SQL1"."DATREG",
         "SQL1"."Date",
         "SQL1"."Week",
         "SQL1"."CDC",
         "SQL1"."Shift",
         "SQL1"."Astro Order #",
         "SQL1"."Short O08",
         "SQL1"."ISOM Order #",
         "SQL1"."TrPac",
         "SQL1"."Article",
         "SQL1"."Supplier",
         "SQL1"."Short L62",
         "SQL1"."Pick MHA",
         "SQL1"."HFB",
         "SQL1"."Short R08",
         "SQL1"."Route Schedule",
         "SQL1"."Plan Date",
         "SQL1"."Shipment #",
         "SQL1"."Receiver",
         "SQL1"."Receiver #",
         "SQL1"."Flow",
         "SQL1"."Reason Code",
         "SQL1"."Reason",
         "SQL1"."Reason Alt Desc",
         "SQL1"."Cancelled By",
         "SQL1"."Log ID (L16T3)"