SELECT DISTINCT "eds"."ITEM_ID" "ITEM_ID",
                "eds"."END_DATE_SALE" "END_DATE_SALE"
FROM "eds"
WHERE "eds"."END_DATE_SALE">=CAST((:PQ1) AS TIMESTAMP)
  AND "eds"."END_DATE_SALE"<=CAST((:PQ2) AS TIMESTAMP)