
SELECT to_char("SHIPMENT_ROUTE"."PLD_END_DATE", 'DD-MON-YYYY HH24:MI:SS') "ShpRou_RecPldArrDateTime",
       concat(concat("SHIPMENT"."BU_CODE_CRE", "SHIPMENT"."BU_TYPE_CRE"), "SHIPMENT"."SHP_NO") "Shp_Id",
       "A_CONSIGNMENT_LINE"."BU_TYPE_RCV" "CsmLine_RcvType_A",
       sum("A_CONSIGNMENT_LINE"."CSL_VOL_NET") "CsmLine_VolNetSum_A"
FROM ((((("LOADING_UNIT_TRIP" "LOADING_UNIT_TRIP"
          INNER JOIN "LOADING_UNIT_TRIP_LEG" "LOADING_UNIT_TRIP_LEG" ON "LOADING_UNIT_TRIP"."BU_CODE_CRE_SHP"="LOADING_UNIT_TRIP_LEG"."BU_CODE_CRE_SHP"
          AND "LOADING_UNIT_TRIP"."BU_TYPE_CRE_SHP"="LOADING_UNIT_TRIP_LEG"."BU_TYPE_CRE_SHP"
          AND "LOADING_UNIT_TRIP"."SHP_NO"="LOADING_UNIT_TRIP_LEG"."SHP_NO")
         INNER JOIN "SHIPMENT" "SHIPMENT" ON "SHIPMENT"."BU_CODE_CRE"="LOADING_UNIT_TRIP"."BU_CODE_CRE_SHP"
         AND "SHIPMENT"."BU_TYPE_CRE"="LOADING_UNIT_TRIP"."BU_TYPE_CRE_SHP"
         AND "SHIPMENT"."SHP_NO"="LOADING_UNIT_TRIP"."SHP_NO")
        INNER JOIN "SHIPMENT_ROUTE" "SHIPMENT_ROUTE" ON "SHIPMENT"."BU_CODE_CRE"="SHIPMENT_ROUTE"."BU_CODE_CRE_SHP"
        AND "SHIPMENT"."BU_TYPE_CRE"="SHIPMENT_ROUTE"."BU_TYPE_CRE_SHP"
        AND "SHIPMENT"."SHP_NO"="SHIPMENT_ROUTE"."SHP_NO")
       INNER JOIN "CONNECTED_CSM" "CONNECTED_CSM" ON "SHIPMENT_ROUTE"."BU_CODE_CRE_SHP"="CONNECTED_CSM"."BU_CODE_CRE_SHP"
       AND "SHIPMENT_ROUTE"."BU_TYPE_CRE_SHP"="CONNECTED_CSM"."BU_TYPE_CRE_SHP"
       AND "SHIPMENT_ROUTE"."SHP_NO"="CONNECTED_CSM"."SHP_NO"
       AND "SHIPMENT_ROUTE"."SHPR_NO"="CONNECTED_CSM"."SHPR_NO")
      INNER JOIN "CONSIGNMENT" "CONSIGNMENT" ON "CONNECTED_CSM"."BU_CODE_CRE_CSM"="CONSIGNMENT"."BU_CODE_CRE"
      AND "CONNECTED_CSM"."BU_TYPE_CRE_CSM"="CONSIGNMENT"."BU_TYPE_CRE"
      AND "CONNECTED_CSM"."CSM_NO"="CONSIGNMENT"."CSM_NO")
LEFT OUTER JOIN "CONSIGNMENT_LINE" "A_CONSIGNMENT_LINE" ON "CONSIGNMENT"."BU_CODE_CRE"="A_CONSIGNMENT_LINE"."BU_CODE_CRE_CSM"
AND "CONSIGNMENT"."BU_TYPE_CRE"="A_CONSIGNMENT_LINE"."BU_TYPE_CRE_CSM"
AND "CONSIGNMENT"."CSM_NO"="A_CONSIGNMENT_LINE"."CSM_NO"
WHERE "CONSIGNMENT"."CSM_STAT"<80
  AND "SHIPMENT"."SHP_STAT" NOT IN (10,
                                    60)
  AND "SHIPMENT_ROUTE"."BU_CODE_END"='390'
  AND "LOADING_UNIT_TRIP_LEG"."MOT_CODE"<>'R'
  AND "SHIPMENT_ROUTE"."BU_TYPE_END"='DT'
  AND TRUNC(cast("SHIPMENT_ROUTE"."PLD_END_DATE" AS TIMESTAMP(9)))=TRUNC(cast(:PQ1 AS TIMESTAMP(9)))
GROUP BY to_char("SHIPMENT_ROUTE"."PLD_END_DATE", 'DD-MON-YYYY HH24:MI:SS'),
         concat(concat("SHIPMENT"."BU_CODE_CRE", "SHIPMENT"."BU_TYPE_CRE"), "SHIPMENT"."SHP_NO"),
         "A_CONSIGNMENT_LINE"."BU_TYPE_RCV"