
SELECT substr("L62T17"."PARTNO", 1, 8),
       trim(BOTH
            FROM "L62T17"."PARTREV"),
       "L62T17"."PARTDSC2",
       trim(BOTH
            FROM "L62T17"."PARTNO")
FROM
  (SELECT "L62T1"."PARTDSC2" "PARTDSC2",
          "L62T1"."PARTNO" "PARTNO",
          "L62T1"."PARTREV" "PARTREV"
   FROM "L62T1" "L62T1"
   WHERE trim(BOTH
              FROM "L62T1"."DIVCODE") NOT IN ('021')) "L62T17"
SELECT "A_PRICES_L62T1"."PRICE",
       "A_PRICES_L62T1"."ITEM_NO",
       "A_PRICES_L62T1"."BU_CODE_SUP", (coalesce("A_PRICES_L62T1"."BU_TYPE_SUP", 'SUP'))
FROM
  (SELECT "PRICES_VW"."ITEM_TYPE" "ITEM_TYPE",
          "PRICES_VW"."ITEM_NO" "ITEM_NO",
          "PRICES_VW"."BU_TYPE_SUP" "BU_TYPE_SUP",
          "PRICES_VW"."BU_CODE_SUP" "BU_CODE_SUP",
          "PRICES_VW"."PRICE" "PRICE"
   FROM "PRICES_VW" "PRICES_VW"
   WHERE "PRICES_VW"."BU_TYPE"='CDC'
     AND "PRICES_VW"."BU_CODE" IN ('053')
     AND "PRICES_VW"."ITEM_TYPE"='ART') "A_PRICES_L62T1"
SELECT AL2.PARTNO,
       AL2.PARTREV,
       AL2.PARTDSC1,
       AL2.DIVCODE,
       AL3.MHA,
       AL3.RACK,
       AL3.HORCOOR,
       AL3.VERCOOR,
       AL1.ECARRNO,
       AL1.AMOONCR,
       AL1.LOCKCODE
FROM AST021.G08T1 AL1,
     AST021.L62T1 AL2,
     AST021.L34T1 AL3
WHERE (AL1.SHORTL62 = AL2.SHORTL62
       AND AL3.MHA = AL1.MHA
       AND AL3.RACK = AL1.RACK
       AND AL3.HORCOOR = AL1.HORCOOR
       AND AL3.VERCOOR = AL1.VERCOOR
       AND AL3.CARRNO = AL1.CARRNO)
  AND (AL1.CARRSTAT IN (5,
                        6)
       AND TRIM(AL2.DIVCODE) = '053'
       AND TRIM(AL2.partno) <> 'TOTE')