
SELECT TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))) "STOChgDate",
       "BO_PALL_CHG_LOG_V"."ART_NO" "STOChgArtNo",
       "BO_PALL_CHG_LOG_V"."SUP_NO" "STOChgSupNo",
       "BO_PALL_CHG_LOG_V"."PALL_ID" "STOChgPallid",
       "BO_PALL_CHG_LOG_V"."CHG_TYPE" "STOChgTyp",
       "BO_PALL_CHG_LOG_V"."ART_QTY" "STOChgQty",
       sum(decode("BO_PALL_CHG_LOG_V"."CHG_TYPE", '390', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '391', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '394', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '392', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '393', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '305', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '306', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '307', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", 0)) "STODamages",
       abs(sum(decode("BO_PALL_CHG_LOG_V"."CHG_TYPE", '390', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '391', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '394', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '392', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '393', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '305', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '306', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", '307', "BO_PALL_CHG_LOG_V"."ART_PRICE_INVE"*"BO_PALL_CHG_LOG_V"."ART_QTY", 0))) "Absolute__STODamages_"
FROM "BO_PALL_CHG_LOG_V" "BO_PALL_CHG_LOG_V"
WHERE "BO_PALL_CHG_LOG_V"."CHG_TYPE" IN ('391',
                                         '392',
                                         '393',
                                         '305',
                                         '395')
  AND TRUNC(cast(TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))) AS TIMESTAMP(9))) BETWEEN (TRUNC(CURRENT_DATE) + (INTERVAL '1' DAY * (-1))) AND TRUNC(CURRENT_DATE)
GROUP BY TRUNC(cast("BO_PALL_CHG_LOG_V"."CHG_DATE" AS TIMESTAMP(9))),
         "BO_PALL_CHG_LOG_V"."ART_NO",
         "BO_PALL_CHG_LOG_V"."SUP_NO",
         "BO_PALL_CHG_LOG_V"."PALL_ID",
         "BO_PALL_CHG_LOG_V"."CHG_TYPE",
         "BO_PALL_CHG_LOG_V"."ART_QTY"