SELECT "ADMUNIT" "IMR_ADMUNIT",
       "PRIORITY" "IMR_PRIO",
       SUBSTR("PRIORITY", 1, 8) "C3",
       CASE
           WHEN "ADMUNIT" IN ('O1A4N',
                                      'R1A4P',
                                      'O1AQ5',
                                      'O1B4N',
                                      'R1B4P',
                                      'O1BQ5',
                                      'O1BA2',
                                      'O1AA1',
                                      'O1AB1',
                                      'O1AA2',
                                      'O1AB2',
                                      'O1A31',
                                      'O1A33',
                                      'O1AA4',
                                      'O1AB4',
                                      'O1AA5',
                                      'O1AB5',
                                      'O1A32',
                                      'O1A34',
                                      '1BA1',
                                      'O1BB1',
                                      'O1BA2',
                                      'O1BB2',
                                      'O1B31',
                                      'O1B33',
                                      'O1BA4',
                                      'O1BB4',
                                      'O1BA5',
                                      'O1BB5',
                                      'O1B32',
                                      'O1B34') THEN '1AB'
           WHEN "ADMUNIT" IN ('O2A4N',
                                      'R2A4P',
                                      'O2AQ5',
                                      'O2AA2',
                                      'O2B4N',
                                      'R2B4P',
                                      'O2BQ5',
                                      'O2BA2',
                                      'O2AA1',
                                      'O2AB1',
                                      'O2AA2',
                                      'O2AB2',
                                      'O2A31',
                                      'O2A33',
                                      'O2AA4',
                                      'O2AB4',
                                      'O2AA5',
                                      'O2AB5',
                                      'O2A32',
                                      'O2A34',
                                      'O2BA1',
                                      'O2BB1',
                                      'O2BA2',
                                      'O2BB2',
                                      'O2B31',
                                      'O2B33',
                                      'O2BA4',
                                      'O2BB4',
                                      'O2BA5',
                                      'O2BB5',
                                      'O2B32',
                                      'O2B34',
                                      'TG231',
                                      'TG233',
                                      'TG2A4') THEN '2AB'
           WHEN "ADMUNIT" IN ('O4A4N',
                                      'R4A4P',
                                      'O4AQ5',
                                      'O4AA2',
                                      'O4B4N',
                                      'R4B4P',
                                      'O4BQ5',
                                      'O4BA2',
                                      'O4AA1',
                                      'O4AB1',
                                      'O4AA2',
                                      'O4AB2',
                                      'O4A31',
                                      'O4A33',
                                      'O4AA4',
                                      'O4AB4',
                                      'O4AA5',
                                      'O4AB5',
                                      'O4A32',
                                      'O4A34',
                                      'O4BA1',
                                      'O4BB1',
                                      'O4BA2',
                                      'O4BB2',
                                      'O4B31',
                                      'O4B33',
                                      'O4BA4',
                                      'O4BB4',
                                      'O4BA5',
                                      'O4BB5',
                                      'O4B32',
                                      'O4B34',
                                      'TG431',
                                      'TG433',
                                      'O4N31',
                                      'O4N33',
                                      'O4N32',
                                      'O4N34',
                                      'O4A5B',
                                      'O4NA4',
                                      'O4NB2') THEN '4AB'
           WHEN "ADMUNIT" IN ('O5A4N',
                                      'R5A4P',
                                      'O5AQ5',
                                      'O5AA2',
                                      'O5B4N',
                                      'R5B4P',
                                      'O5BQ5',
                                      'O5BA2',
                                      'O5AA1',
                                      'O5AB1',
                                      'O5AA2',
                                      'O5AB2',
                                      'O5A31',
                                      'O5A33',
                                      'O5AA4',
                                      'O5AB4',
                                      'O5AA5',
                                      'O5AB5',
                                      'O5A32',
                                      'O5A34',
                                      'O5BA1',
                                      'O5BB1',
                                      'O5BA2',
                                      'O5BB2',
                                      'O5B31',
                                      'O5B33',
                                      'O5BA4',
                                      'O5BB4',
                                      'O5BA5',
                                      'O5BB5',
                                      'O5B32',
                                      'O5B34',
                                      'O5B5B') THEN '5AB'
           WHEN "ADMUNIT" IN ('R4A4P',
                                      'R4B4P',
                                      'T4P  ',
                                      'R4A4N',
                                      'R4B4N',
                                      'R4N4P') THEN 'REP'
           WHEN "ADMUNIT" IN ('IA131',
                                      'IA132',
                                      'IA134',
                                      'IA231',
                                      'IA232',
                                      'IA233',
                                      'IA234',
                                      'IA431',
                                      'IA433',
                                      'IA434',
                                      'IB131',
                                      'IB132',
                                      'IB134',
                                      'IB231',
                                      'IB233',
                                      'IB431',
                                      'IB432',
                                      'IB433',
                                      'IB434') THEN '1MT'
       END "C4",
       COUNT("L54UNIQ") "ASSIGNMENT_COUNT"
FROM "L54T1" "L54T1",
     "G08T1" "A_G08T1_L54"
WHERE "ADMUNIT" NOT IN ('O301',
                                'O303',
                                'O305',
                                'O307',
                                'O309',
                                'O311',
                                'O312',
                                'O315',
                                'O317',
                                'O319',
                                'O321')
  AND "L54STATE" IN (1,
                             2)
  AND "L54TYPE" IN (3,
                            18,
                            27)
  AND ("ADMUNIT" LIKE 'T%'
       OR ("ADMUNIT" LIKE 'IB%'
           OR "ADMUNIT" LIKE 'IA%')
       AND "L54TYPE"<>'3'
       OR "ADMUNIT" LIKE 'O%'
       OR "ADMUNIT" LIKE 'R%')
  AND "ADMUNIT" NOT  LIKE 'TS%'
  AND "ADMUNIT"<>'O3S'
  AND "ADMUNIT" NOT IN ('R4P4P')
  AND "ADMUNIT" NOT  LIKE '%2B'
  AND "ADMUNIT" NOT  LIKE '%1B'
  AND "ADMUNIT" NOT  LIKE '%4B'
  AND "ADMUNIT" NOT  LIKE '%5B'
  AND "ADMUNIT" NOT  LIKE '%1A'
  AND "ADMUNIT" NOT  LIKE '%2A'
  AND "ADMUNIT" NOT  LIKE 'TH%'
  AND "ADMUNIT" NOT  LIKE '%3S'
  AND "ADMUNIT" NOT  LIKE 'TC4%'
  AND "MHA" NOT IN ('AVIN',
                                  'AVOUT',
                                  'EMBAL',
                                  'PM')
  AND "ADMUNIT"<>'T4C4C'
  AND "ADMUNIT" NOT  LIKE '%4A'
  AND "ADMUNIT" NOT  LIKE '%5A'
  AND "CARRNO"="CARRNO"
GROUP BY "ADMUNIT",
         "PRIORITY",
         SUBSTR("PRIORITY", 1, 8),
         CASE
             WHEN "ADMUNIT" IN ('O1A4N',
                                        'R1A4P',
                                        'O1AQ5',
                                        'O1B4N',
                                        'R1B4P',
                                        'O1BQ5',
                                        'O1BA2',
                                        'O1AA1',
                                        'O1AB1',
                                        'O1AA2',
                                        'O1AB2',
                                        'O1A31',
                                        'O1A33',
                                        'O1AA4',
                                        'O1AB4',
                                        'O1AA5',
                                        'O1AB5',
                                        'O1A32',
                                        'O1A34',
                                        '1BA1',
                                        'O1BB1',
                                        'O1BA2',
                                        'O1BB2',
                                        'O1B31',
                                        'O1B33',
                                        'O1BA4',
                                        'O1BB4',
                                        'O1BA5',
                                        'O1BB5',
                                        'O1B32',
                                        'O1B34') THEN '1AB'
             WHEN "ADMUNIT" IN ('O2A4N',
                                        'R2A4P',
                                        'O2AQ5',
                                        'O2AA2',
                                        'O2B4N',
                                        'R2B4P',
                                        'O2BQ5',
                                        'O2BA2',
                                        'O2AA1',
                                        'O2AB1',
                                        'O2AA2',
                                        'O2AB2',
                                        'O2A31',
                                        'O2A33',
                                        'O2AA4',
                                        'O2AB4',
                                        'O2AA5',
                                        'O2AB5',
                                        'O2A32',
                                        'O2A34',
                                        'O2BA1',
                                        'O2BB1',
                                        'O2BA2',
                                        'O2BB2',
                                        'O2B31',
                                        'O2B33',
                                        'O2BA4',
                                        'O2BB4',
                                        'O2BA5',
                                        'O2BB5',
                                        'O2B32',
                                        'O2B34',
                                        'TG231',
                                        'TG233',
                                        'TG2A4') THEN '2AB'
             WHEN "ADMUNIT" IN ('O4A4N',
                                        'R4A4P',
                                        'O4AQ5',
                                        'O4AA2',
                                        'O4B4N',
                                        'R4B4P',
                                        'O4BQ5',
                                        'O4BA2',
                                        'O4AA1',
                                        'O4AB1',
                                        'O4AA2',
                                        'O4AB2',
                                        'O4A31',
                                        'O4A33',
                                        'O4AA4',
                                        'O4AB4',
                                        'O4AA5',
                                        'O4AB5',
                                        'O4A32',
                                        'O4A34',
                                        'O4BA1',
                                        'O4BB1',
                                        'O4BA2',
                                        'O4BB2',
                                        'O4B31',
                                        'O4B33',
                                        'O4BA4',
                                        'O4BB4',
                                        'O4BA5',
                                        'O4BB5',
                                        'O4B32',
                                        'O4B34',
                                        'TG431',
                                        'TG433',
                                        'O4N31',
                                        'O4N33',
                                        'O4N32',
                                        'O4N34',
                                        'O4A5B',
                                        'O4NA4',
                                        'O4NB2') THEN '4AB'
             WHEN "ADMUNIT" IN ('O5A4N',
                                        'R5A4P',
                                        'O5AQ5',
                                        'O5AA2',
                                        'O5B4N',
                                        'R5B4P',
                                        'O5BQ5',
                                        'O5BA2',
                                        'O5AA1',
                                        'O5AB1',
                                        'O5AA2',
                                        'O5AB2',
                                        'O5A31',
                                        'O5A33',
                                        'O5AA4',
                                        'O5AB4',
                                        'O5AA5',
                                        'O5AB5',
                                        'O5A32',
                                        'O5A34',
                                        'O5BA1',
                                        'O5BB1',
                                        'O5BA2',
                                        'O5BB2',
                                        'O5B31',
                                        'O5B33',
                                        'O5BA4',
                                        'O5BB4',
                                        'O5BA5',
                                        'O5BB5',
                                        'O5B32',
                                        'O5B34',
                                        'O5B5B') THEN '5AB'
             WHEN "ADMUNIT" IN ('R4A4P',
                                        'R4B4P',
                                        'T4P  ',
                                        'R4A4N',
                                        'R4B4N',
                                        'R4N4P') THEN 'REP'
             WHEN "ADMUNIT" IN ('IA131',
                                        'IA132',
                                        'IA134',
                                        'IA231',
                                        'IA232',
                                        'IA233',
                                        'IA234',
                                        'IA431',
                                        'IA433',
                                        'IA434',
                                        'IB131',
                                        'IB132',
                                        'IB134',
                                        'IB231',
                                        'IB233',
                                        'IB431',
                                        'IB432',
                                        'IB433',
                                        'IB434') THEN '1MT'
         END
ORDER BY "C4" ASC NULLS LAST