SELECT "IN_CONT_NO" AS "IN_CONT_NO",
       "C2" AS "C2",
       "C3" AS "C3",
       "C4" AS "C4",
       "G_TRIP_TYPE" AS "G_TRIP_TYPE",
       "G_ROUTE" AS "G_ROUTE",
       "G_SHOW_CONTAINER" AS "G_SHOW_CONTAINER",
       "COMPUTED" AS "COMPUTED",
       "UNIT_SIZE" AS "UNIT_SIZE",
       "BILL_OF_LADING_NO" AS "BILL_OF_LADING_NO",
       "BUCODEDTGCT" AS "BUCODEDTGCT",
       "BU_CODE_CRE_SHP" AS "BU_CODE_CRE_SHP",
       "BU_TYPE_CRE_SHP" AS "BU_TYPE_CRE_SHP",
       "BU_TYPE_DT" AS "BU_TYPE_DT",
       "SHP_NO" AS "SHP_NO",
       "LUTR_NO" AS "LUTR_NO",
       "CUSTOMS_CLEAR_DATE" AS "CUSTOMS_CLEAR_DATE",
       "PLAN_END_DATE" AS "PLAN_END_DATE",
       "ACT_END_DATE" AS "ACT_END_DATE",
       "PLAN_START_DATE" AS "PLAN_START_DATE",
       "ACT_START_DATE" AS "ACT_START_DATE",
       "BU_CODE_START" AS "BU_CODE_START",
       "BU_TYPE_START" AS "BU_TYPE_START",
       "BUA_NO_START" AS "BUA_NO_START",
       "BU_CODE_END" AS "BU_CODE_END",
       "BU_TYPE_END" AS "BU_TYPE_END",
       "BUA_NO_END" AS "BUA_NO_END",
       "BU_NAME_CAR" AS "BU_NAME_CAR",
       "VOYAGE_NO" AS "VOYAGE_NO",
       "TRPU_ID" AS "TRPU_ID",
       "C30" AS "C31",
       "COMMENTS" AS "COMMENTS",
       "C32" AS "C33",
       "CNS_COMMENTS" AS "CNS_COMMENTS",
       "INSTATUSGCT" AS "INSTATUSGCT",
       "NAMEGISD" AS "NAMEGISD",
       "IN_STATUS" AS "IN_STATUS",
       "NAME" AS "NAME",
       "SHP_STAT" AS "SHP_STAT",
       "BU_CODE_DT" AS "BU_CODE_DT",
       "AVAIL_TIME_CUSORD" AS "AVAIL_TIME_CUSORD",
       "C41" AS "C42",
       "C42" AS "C43"
FROM "SQ0_GEMINI__GEM_",
     "TQ0_GEMINI__GEM_"
WHERE "IN_CONT_NO" = "IN_CONT_NO"
  AND ("C2" = "C2"
       OR ("C2" IS NULL
           AND "C2" IS NULL))
  AND ("C3" = "C3"
       OR ("C3" IS NULL
           AND "C3" IS NULL))
  AND ("C4" = "C4"
       OR ("C4" IS NULL
           AND "C4" IS NULL))
  AND "G_TRIP_TYPE" = "G_TRIP_TYPE"
  AND ("G_ROUTE" = "G_ROUTE"
       OR ("G_ROUTE" IS NULL
           AND "G_ROUTE" IS NULL))
  AND "G_SHOW_CONTAINER" = "G_SHOW_CONTAINER"
  AND "COMPUTED" = "COMPUTED"
  AND ("UNIT_SIZE" = "UNIT_SIZE"
       OR ("UNIT_SIZE" IS NULL
           AND "UNIT_SIZE" IS NULL))
  AND ("BILL_OF_LADING_NO" = "BILL_OF_LADING_NO"
       OR ("BILL_OF_LADING_NO" IS NULL
           AND "BILL_OF_LADING_NO" IS NULL))
  AND "BUCODEDTGCT" = "BUCODEDTGCT"
  AND "BU_CODE_CRE_SHP" = "BU_CODE_CRE_SHP"
  AND "BU_TYPE_CRE_SHP" = "BU_TYPE_CRE_SHP"
  AND "BU_TYPE_DT" = "BU_TYPE_DT"
  AND "LUTR_NO" = "LUTR_NO"
  AND ("CUSTOMS_CLEAR_DATE" = "CUSTOMS_CLEAR_DATE"
       OR ("CUSTOMS_CLEAR_DATE" IS NULL
           AND "CUSTOMS_CLEAR_DATE" IS NULL))
  AND ("PLAN_END_DATE" = "PLAN_END_DATE"
       OR ("PLAN_END_DATE" IS NULL
           AND "PLAN_END_DATE" IS NULL))
  AND ("ACT_END_DATE" = "ACT_END_DATE"
       OR ("ACT_END_DATE" IS NULL
           AND "ACT_END_DATE" IS NULL))
  AND ("PLAN_START_DATE" = "PLAN_START_DATE"
       OR ("PLAN_START_DATE" IS NULL
           AND "PLAN_START_DATE" IS NULL))
  AND ("ACT_START_DATE" = "ACT_START_DATE"
       OR ("ACT_START_DATE" IS NULL
           AND "ACT_START_DATE" IS NULL))
  AND ("BU_CODE_START" = "BU_CODE_START"
       OR ("BU_CODE_START" IS NULL
           AND "BU_CODE_START" IS NULL))
  AND ("BU_TYPE_START" = "BU_TYPE_START"
       OR ("BU_TYPE_START" IS NULL
           AND "BU_TYPE_START" IS NULL))
  AND ("BUA_NO_START" = "BUA_NO_START"
       OR ("BUA_NO_START" IS NULL
           AND "BUA_NO_START" IS NULL))
  AND "BU_CODE_END" = "BU_CODE_END"
  AND "BU_TYPE_END" = "BU_TYPE_END"
  AND ("BUA_NO_END" = "BUA_NO_END"
       OR ("BUA_NO_END" IS NULL
           AND "BUA_NO_END" IS NULL))
  AND ("BU_NAME_CAR" = "BU_NAME_CAR"
       OR ("BU_NAME_CAR" IS NULL
           AND "BU_NAME_CAR" IS NULL))
  AND ("VOYAGE_NO" = "VOYAGE_NO"
       OR ("VOYAGE_NO" IS NULL
           AND "VOYAGE_NO" IS NULL))
  AND ("TRPU_ID" = "TRPU_ID"
       OR ("TRPU_ID" IS NULL
           AND "TRPU_ID" IS NULL))
  AND ("C30" = "C30"
       OR ("C30" IS NULL
           AND "C30" IS NULL))
  AND ("COMMENTS" = "COMMENTS"
       OR ("COMMENTS" IS NULL
           AND "COMMENTS" IS NULL))
  AND "C32" = "C32"
  AND ("CNS_COMMENTS" = "CNS_COMMENTS"
       OR ("CNS_COMMENTS" IS NULL
           AND "CNS_COMMENTS" IS NULL))
  AND "INSTATUSGCT" = "INSTATUSGCT"
  AND "NAMEGISD" = "NAMEGISD"
  AND "IN_STATUS" = "IN_STATUS"
  AND "NAME" = "NAME"
  AND "SHP_STAT" = "SHP_STAT"
  AND "BU_CODE_DT" = "BU_CODE_DT"
  AND ("AVAIL_TIME_CUSORD" = "AVAIL_TIME_CUSORD"
       OR ("AVAIL_TIME_CUSORD" IS NULL
           AND "AVAIL_TIME_CUSORD" IS NULL))
  AND ("C41" = "C41"
       OR ("C41" IS NULL
           AND "C41" IS NULL))