SELECT DISTINCT TRIM(BOTH
                     FROM "PARTNO") "ARTNO",
                TRIM(BOTH
                     FROM "PARTREV") "ARTSUPNO",
                "CPLEN" "ARTSYS_LENGTH",
                "CPWID" "ARTSYS_WIDTH",
                "CPHEI" "ARTSYS_HEIGHT",
                "SUVOL" "ARTSYS_VOLUMEGRO"
FROM "L62T14",
     "DWPACTPK" "DWPACTPK",
     "L62T995",
     "DWPKEY" "DWPKEY"
WHERE "PARTNO"="PARTNO"
  AND "PARTREV"="PARTREV"
  AND "DIVCODE"="DIVCODE"
  AND "SHORTDWP"="SHORTDWP"
  AND "ITEMNO"="ITEMNO"
  AND "ITEMTYPE"="ITEMTYPE"
  AND "REQDWPNO"="REQDWPNO"
  AND "REQDWPED"="REQDWPED"
  AND "BUCODSUP"="BUCODSUP"
  AND "BUTYPSUP"="BUTYPSUP"
  AND "FPACDATE"="FPACDATE"