SELECT SUM("ECARRNO") AS "ECARRNO",
       "UNITCD" AS "UNITCD",
       CASE
           WHEN "UNITCD" IN ('AT110',
                                    'AT120',
                                    'AT130',
                                    'AT140',
                                    'AT160',
                                    'AT210',
                                    'AT220',
                                    'AT230',
                                    'AT240',
                                    'AT260',
                                    'AT310',
                                    'AT320',
                                    'AT330',
                                    'AT410',
                                    'AT420',
                                    'AT430',
                                    'AT460',
                                    'AT510',
                                    'AT610',
                                    'AT630',
                                    'AT710',
                                    'AT99',
                                    'AU220',
                                    'AU330',
                                    'AU340',
                                    'AU420',
                                    'AU450',
                                    'AU710',
                                    'AW130',
                                    'AW140',
                                    'AW240',
                                    'AW250',
                                    'AW260',
                                    'AW290',
                                    'AW320',
                                    'AX140',
                                    'AX160',
                                    'AX240',
                                    'AX250',
                                    'AX310',
                                    'AX410',
                                    'AX440',
                                    'AX610',
                                    'AX710') THEN 'EURO'
           WHEN "UNITCD" IN ('BT110',
                                    'BT120',
                                    'BT210',
                                    'BT420',
                                    'BT510') THEN 'HALF'
           ELSE 'IKEA'
       END AS "PAL_TYPE"
FROM "SQL1"
GROUP BY "UNITCD",
         CASE
             WHEN "UNITCD" IN ('AT110',
                                      'AT120',
                                      'AT130',
                                      'AT140',
                                      'AT160',
                                      'AT210',
                                      'AT220',
                                      'AT230',
                                      'AT240',
                                      'AT260',
                                      'AT310',
                                      'AT320',
                                      'AT330',
                                      'AT410',
                                      'AT420',
                                      'AT430',
                                      'AT460',
                                      'AT510',
                                      'AT610',
                                      'AT630',
                                      'AT710',
                                      'AT99',
                                      'AU220',
                                      'AU330',
                                      'AU340',
                                      'AU420',
                                      'AU450',
                                      'AU710',
                                      'AW130',
                                      'AW140',
                                      'AW240',
                                      'AW250',
                                      'AW260',
                                      'AW290',
                                      'AW320',
                                      'AX140',
                                      'AX160',
                                      'AX240',
                                      'AX250',
                                      'AX310',
                                      'AX410',
                                      'AX440',
                                      'AX610',
                                      'AX710') THEN 'EURO'
             WHEN "UNITCD" IN ('BT110',
                                      'BT120',
                                      'BT210',
                                      'BT420',
                                      'BT510') THEN 'HALF'
             ELSE 'IKEA'
         END